# **Import Dataset**

In [ ]:
import pandas as pd
import numpy as np
import nltk
import string
import re
import math

In [ ]:
from google.colab import files
filecolab = files.upload()
for fn in filecolab.keys():
  print('Nama file "name" dengan panjang {length} bytes'.format(
      name=fn, length=len(filecolab [fn])
  ))

In [ ]:
df = pd.read_csv('datatraining.csv', encoding='cp1252')

In [ ]:
df

                                                d1(0)                                              d2(1)
0   April 2020 Ternyata untuk pembayaran masih d a...  Pernah bawa surat rujukan ke specialis mata di...
1   Performa aplikasi masi sangat lambat padhal su...  Bagus. Hanya saja bikin kesel soalnya minta di...
2   Aplikasi tolong donk dibenerin kok eror mulu u...  sangat membatu sekali saya bisa mengecek sudah...
3   Ini aplikasi gak bener Sudah daptar lama tapi ...  reset password mengenali email. daftar baru st...
4   aplikasi ini di perbaharui download ulang lagi...  Aplikasi ini sangat membantu di kalah mau mend...
5   Ok lah.... tp tarf iuran knp dinaikan kelas pa...  Peningkatan yang signifikan. Lanjutkan. Info K...
6   Dengan berat hati saya kecewa dengan kebijakan...  Bagus.aplikasi ini sangat membantu bagi pemega...
7   Dulu lancar2 aja. Skrg dikit2 update tiap mau ...  Aplikasinya sangat membantu terima kasih mobil...
8   Tidak bisa login....iuran naik, kualitas nol. ...  keren ada riwayat pelayanan tapi anak dan istr...
9   Program kesehatan nasional gundulmu. Kalau mer...  Mohon dibantu agar aplikasi JKN bisa dibuka .M...
10  Tidak bisa daftar akun saat memasukkan email d...           Lumayan membantu dgn adanya aplikasi ini
11  Di update malah gk bisa di akses... Cacha nya ...  Lebih keren lagi seandainya ada menu untuk pen...
12  Saya baru download tetapi untuk daftar online ...  Kenapa ya kalo udh terdaftar kok gabisa buat m...
13  Tolong di bantu, kenapa tidak bisa login. Saat...  Gimana sih cara merubah tanggal lahir peserta ...
14  Aplikasi tiba tiba terhenti pada saat pilih me...  bermanfaat sekali....tolong jaga kualitas pela...

# **Preprocessing**

## 1. Tokenisasi

In [ ]:
def hapusTandaBaca(text):
    return re.sub(r'[^\w\s]', '', text)

def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

def remove_spasi(text):
    return " ".join(text.split())

def remove(text):
    remove_angka = re.sub('[0-9]+', '', text)
    return remove_angka

In [ ]:
df["d1(0)"] = df["d1(0)"] .apply(lambda x: hapusTandaBaca(x)) \
                          .apply(lambda x: x.lower()) \
                          .apply(lambda x: remove_emoji(x)) \
                          .apply(lambda x: remove_spasi(x)) \
                          .apply(lambda x: remove(x)) \
                          .apply(lambda x: x.strip())
                          


df["d2(1)"] = df["d2(1)"] .apply(lambda x: hapusTandaBaca(x)) \
                          .apply(lambda x: x.lower()) \
                          .apply(lambda x: remove_emoji(x)) \
                          .apply(lambda x: remove_spasi(x)) \
                          .apply(lambda x: remove(x)) \
                          .apply(lambda x: x.strip())

In [ ]:
df

                                                d1(0)                                              d2(1)
0   april  ternyata untuk pembayaran masih d angka...  pernah bawa surat rujukan ke specialis mata di...
1   performa aplikasi masi sangat lambat padhal su...  bagus hanya saja bikin kesel soalnya minta dip...
2   aplikasi tolong donk dibenerin kok eror mulu u...  sangat membatu sekali saya bisa mengecek sudah...
3   ini aplikasi gak bener sudah daptar lama tapi ...  reset password mengenali email daftar baru sta...
4   aplikasi ini di perbaharui download ulang lagi...  aplikasi ini sangat membantu di kalah mau mend...
5   ok lah tp tarf iuran knp dinaikan kelas paling...  peningkatan yang signifikan lanjutkan info kam...
6   dengan berat hati saya kecewa dengan kebijakan...  bagusaplikasi ini sangat membantu bagi pemegan...
7   dulu lancar aja skrg dikit update tiap mau buk...  aplikasinya sangat membantu terima kasih mobil...
8   tidak bisa loginiuran naik kualitas nol perbai...  keren ada riwayat pelayanan tapi anak dan istr...
9   program kesehatan nasional gundulmu kalau mera...  mohon dibantu agar aplikasi jkn bisa dibuka mo...
10  tidak bisa daftar akun saat memasukkan email d...           lumayan membantu dgn adanya aplikasi ini
11  di update malah gk bisa di akses cacha nya gk ...  lebih keren lagi seandainya ada menu untuk pen...
12  saya baru download tetapi untuk daftar online ...  kenapa ya kalo udh terdaftar kok gabisa buat m...
13  tolong di bantu kenapa tidak bisa login saat a...  gimana sih cara merubah tanggal lahir peserta ...
14  aplikasi tiba tiba terhenti pada saat pilih me...  bermanfaat sekalitolong jaga kualitas pelayana...

In [ ]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="x", filters='_!"#$%&()*+.,-/:;=?@[\]^_`{|}~ ')
tokenizer.fit_on_texts(df["d1(0)"])
tokenizer.fit_on_texts(df["d2(1)"])

## 2. Stopwords Removal

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stopIndo = set(stopwords.words('indonesian'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
extend = ["blm","bln","blum","cieh","des",
          "donk","gk","d","dgn","g","gk",
          "jg","jkn","keti","knp","lah","lg",
          "lgi","pdhl","piye","sdh","skrg","sm",
          "spt","tarf","susuah","tk","tks","tp",
          "ttp","udh","yg","ad","bs","klo","my"]

for i in extend:
    stopIndo.add(i)

In [ ]:
df["d1(0)"] = df["d1(0)"].apply(lambda x:' '.join([word for word in x.split() if word not in (stopIndo)]))
df["d2(1)"] = df["d2(1)"].apply(lambda x:' '.join([word for word in x.split() if word not in (stopIndo)]))

In [ ]:
temp_data = []
for i in tokenizer.word_index:
    if i in stopIndo:
        temp_data.append(i)

for i in temp_data:
    if i in tokenizer.word_index:
        tokenizer.word_index.pop(i)

## 3. Stemming

In [ ]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 34.8 MB/s
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# stem
token_words = tokenizer.word_counts

stem_collection = {}

for i in token_words:
    t = stemmer.stem(i)
    stem_collection[i] = t

In [ ]:
stem_collection

{'ad': 'ad',
 'ada': 'ada',
 'adanya': 'ada',
 'adil': 'adil',
 'agar': 'agar',
 'aja': 'aja',
 'akan': 'akan',
 'akhirnya': 'akhir',
 'akses': 'akses',
 'akun': 'akun',
 'anak': 'anak',
 'anda': 'anda',
 'angka': 'angka',
 'antara': 'antara',
 'antrian': 'antri',
 'apa': 'apa',
 'apakah': 'apakah',
 'aplikasi': 'aplikasi',
 'aplikasinya': 'aplikasi',
 'aplilasi': 'aplilasi',
 'app': 'app',
 'april': 'april',
 'atau': 'atau',
 'aturan': 'atur',
 'bagaimana': 'bagaimana',
 'bagi': 'bagi',
 'bagus': 'bagus',
 'bagusaplikasi': 'bagusaplikasi',
 'baik': 'baik',
 'balik': 'balik',
 'banget': 'banget',
 'bantu': 'bantu',
 'bantuannya': 'bantu',
 'banyak': 'banyak',
 'baru': 'baru',
 'bawa': 'bawa',
 'bayar': 'bayar',
 'bayarannya': 'bayar',
 'bayi': 'bayi',
 'beberapa': 'beberapa',
 'bekerja': 'kerja',
 'belum': 'belum',
 'benarbenar': 'benarbenar',
 'bener': 'bener',
 'berat': 'berat',
 'berbagai': 'bagai',
 'berefek': 'efek',
 'berhenti': 'henti',
 'berita': 'berita',
 'bermanfaat': 'manfaat',
 'berulang': 'ulang',
 'berulangulang': 'berulangulang',
 'biar': 'biar',
 'biasa': 'biasa',
 'bikin': 'bikin',
 'bila': 'bila',
 'bintang': 'bintang',
 'bisa': 'bisa',
 'blm': 'blm',
 'bln': 'bln',
 'blum': 'blum',
 'bpjs': 'bpjs',
 'bs': 'bs',
 'buat': 'buat',
 'buka': 'buka',
 'bukan': 'bukan',
 'bulan': 'bulan',
 'cacha': 'cacha',
 'calon': 'calon',
 'cara': 'cara',
 'caranya': 'cara',
 'cek': 'cek',
 'cieh': 'cieh',
 'coba': 'coba',
 'covid': 'covid',
 'd': 'd',
 'daftar': 'daftar',
 'dan': 'dan',
 'dapat': 'dapat',
 'daptar': 'daptar',
 'dari': 'dari',
 'data': 'data',
 'dengan': 'dengan',
 'deposit': 'deposit',
 'des': 'des',
 'dgn': 'dgn',
 'di': 'di',
 'dibantu': 'bantu',
 'dibenerin': 'dibenerin',
 'diblokir': 'blokir',
 'dibohongi': 'bohong',
 'dibuka': 'buka',
 'dicoba': 'coba',
 'dikit': 'dikit',
 'dilayani': 'layan',
 'dinaikan': 'naik',
 'dipakai': 'pakai',
 'diperbarui': 'baru',
 'dipermudah': 'mudah',
 'dipersulit': 'sulit',
 'dipersulitmana': 'dipersulitmana',
 'diproses': 'proses',
 'diri': 'diri',
 'disetor': 'setor',
 'ditekan': 'tekan',
 'ditingkatkan': 'tingkat',
 'dong': 'dong',
 'dongrakyat': 'dongrakyat',
 'donk': 'donk',
 'download': 'download',
 'dulu': 'dulu',
 'email': 'email',
 'eror': 'eror',
 'erro': 'erro',
 'error': 'error',
 'familier': 'familier',
 'faskes': 'faskes',
 'fiturnya': 'fiturnya',
 'fool': 'fool',
 'g': 'g',
 'ga': 'ga',
 'gabisa': 'gabisa',
 'gak': 'gak',
 'gimana': 'gimana',
 'gini': 'gin',
 'gk': 'gk',
 'gundulmu': 'gundul',
 'hanya': 'hanya',
 'harusnya': 'harus',
 'hati': 'hati',
 'indonesia': 'indonesia',
 'info': 'info',
 'ini': 'ini',
 'iniðÿ': 'ini',
 'istri': 'istri',
 'itu': 'itu',
 'iuran': 'iur',
 'iyuran': 'iyuran',
 'jadi': 'jadi',
 'jadinya': 'jadi',
 'jaga': 'jaga',
 'jam': 'jam',
 'jandes': 'jandes',
 'jangan': 'jangan',
 'jg': 'jg',
 'jkn': 'jkn',
 'juga': 'juga',
 'kadang': 'kadang',
 'kalah': 'kalah',
 'kalau': 'kalau',
 'kali': 'kali',
 'kalo': 'kalo',
 'kamar': 'kamar',
 'kampung': 'kampung',
 'karena': 'karena',
 'kartu': 'kartu',
 'kartumohon': 'kartumohon',
 'kasi': 'kasi',
 'kasih': 'kasih',
 'kata': 'kata',
 'kaya': 'kaya',
 'ke': 'ke',
 'kebijakan': 'bijak',
 'kecewa': 'kecewa',
 'kecil': 'kecil',
 'kelas': 'kelas',
 'keluar': 'keluar',
 'kena': 'kena',
 'kenaikan': 'naik',
 'kenapa': 'kenapa',
 'kepastian': 'pasti',
 'keras': 'keras',
 'keren': 'keren',
 'kesehatan': 'sehat',
 'kesehatanfitur': 'kesehatanfitur',
 'kesel': 'kesel',
 'keti': 'keti',
 'kita': 'kita',
 'klo': 'klo',
 'knp': 'knp',
 'kok': 'kok',
 'kosong': 'kosong',
 'kualitas': 'kualitas',
 'lagi': 'lagi',
 'lagiiiiiiii': 'lagiiiiiiii',
 'lagiulasan': 'lagiulasan',
 'lah': 'lah',
 'lahir': 'lahir',
 'lahujungnya': 'lahujungnya',
 'lama': 'lama',
 'lambat': 'lambat',
 'lancar': 'lancar',
 'lanjutkan': 'lanjut',
 'layaknya': 'layak',
 'lebih': 'lebih',
 'lengkapaplikasi': 'lengkapaplikasi',
 'lengkapdengan': 'lengkapdengan',
 'lengkapok': 'lengkapok',
 'lg': 'lg',
 'lgi': 'lgi',
 'loading': 'loading',
 'login': 'login',
 'loginiuran': 'loginiuran',
 'logo': 'logo',
 'lumayan': 'lumayan',
 'lunas': 'lunas',
 'lunasi': 'lunas',
 'lunasulasan': 'lunasulasan',
 'maaf': 'maaf',
 'makin': 'makin',
 'malah': 'malah',
 'mana': 'mana',
 'masi': 'mas',
 'masih': 'masih',
 'masuk': 'masuk',
 'masukmohon': 'masukmohon',
 'masuknya': 'masuk',
 'masyarakat': 'masyarakat',
 'mata': 'mata',
 'mau': 'mau',
 'media': 'media',
 'melarat': 'melarat',
 'memang': 'memang',
 'memasukkan': 'masuk',
 'membantu': 'bantu',
 'membatu': 'batu',
 'membutuhkan': 'butuh',
 'mempermudah': 'mudah',
 'mendaftar': 'daftar',
 'mengecek': 'ecek',
 'mengeluh': 'keluh',
 'mengenakkan': 'enak',
 'mengenali': 'nali',
 'menu': 'menu',
 'menyebar': 'sebar',
 'merantau': 'rantau',
 'merubah': 'rubah',
 'minta': 'minta',
 'mobile': 'mobile',
 'mohon': 'mohon',
 'mudah': 'mudah',
 'mulu': 'mulu',
 'muncul': 'muncul',
 'my': 'my',
 'naik': 'naik',
 'naikan': 'naik',
 'namun': 'namun',
 'nasional': 'nasional',
 'ngikut': 'ngikut',
 'ngrasa': 'ngrasa',
 'nol': 'nol',
 'nomer': 'nomer',
 'notif': 'notif',
 'nya': 'nya',
 'ok': 'ok',
 'oke': 'oke',
 'online': 'online',
 'pada': 'pada',
 'padahal': 'padahal',
 'padhal': 'padhal',
 'pagi': 'pagi',
 'paling': 'paling',
 'pasien': 'pasien',
 'password': 'password',
 'paswordnya': 'paswordnya',
 'pdahal': 'pdahal',
 'pdhl': 'pdhl',
 'pelayanan': 'layan',
 'pelayanannya': 'layan',
 'pembayaran': 'bayar',
 'pemegang': 'pegang',
 'pemerintah': 'perintah',
 'pencerahan': 'cerah',
 'pendaftaran': 'daftar',
 'penilaian': 'nilai',
 'peningkatan': 'tingkat',
 'penjelasan': 'jelas',
 'perah': 'perah',
 'peraturan': 'atur',
 'perbaharui': 'baharu',
 'perbaiki': 'baik',
 'performa': 'performa',
 'periksa': 'periksa',
 'pernah': 'pernah',
 'perusahan': 'usah',
 'pesan': 'pesan',
 'peserta': 'serta',
 'pilih': 'pilih',
 'piye': 'piye',
 'premi': 'premi',
 'program': 'program',
 'proses': 'proses',
 'prosessilahkan': 'prosessilahkan',
 'protes': 'protes',
 'puluhan': 'puluh',
 'puskesmasrumah': 'puskesmasrumah',
 'rakyat': 'rakyat',
 'reset': 'reset',
 'respon': 'respon',
 'ribet': 'ribet',
 'riwayat': 'riwayat',
 'rubah': 'rubah',
 'rujukan': 'rujuk',
 'rumah': 'rumah',
 'saat': 'saat',
 'saja': 'saja',
 'sakit': 'sakit',
 'salah': 'salah',
 'saldo': 'saldo',
 'sama': 'sama',
 'sandi': 'sandi',
 'sangat': 'sangat',
 'sanksi': 'sanksi',
 'saulasan': 'saulasan',
 'saya': 'saya',
 'sdh': 'sdh',
 'seandainya': 'anda',
 'sebelum': 'belum',
 'sebelumnya': 'belum',
 'segera': 'segera',
 'sekali': 'sekali',
 'sekalitolong': 'sekalitolong',
 'sekarang': 'sekarang',
 'selalu': 'selalu',
 'seperti': 'seperti',
 'signifikan': 'signifikan',
 'sih': 'sih',
 'silahkan': 'silah',
 'simpan': 'simpan',
 'skrg': 'skrg',
 'sm': 'sm',
 'soalnya': 'soal',
 'solusinya': 'solusi',
 'specialis': 'specialis',
 'spt': 'spt',
 'status': 'status',
 'sudah': 'sudah',
 'sulit': 'sulit',
 'surat': 'surat',
 'susah': 'susah',
 'susuah': 'susuah',
 'tanggal': 'tanggal',
 'tapi': 'tapi',
 'tarf': 'tarf',
 'tarif': 'tarif',
 'tempat': 'tempat',
 'terdaftar': 'daftar',
 'terdekatpraktis': 'terdekatpraktis',
 'terhenti': 'henti',
 'terima': 'terima',
 'terkait': 'kait',
 'ternyata': 'nyata',
 'terus': 'terus',
 'tetap': 'tetap',
 'tetapi': 'tetapi',
 'tiap': 'tiap',
 'tiba': 'tiba',
 'tidak': 'tidak',
 'tk': 'tk',
 'tks': 'tks',
 'tokped': 'tokped',
 'tolong': 'tolong',
 'tp': 'tp',
 'transaksi': 'transaksi',
 'trial': 'trial',
 'trus': 'trus',
 'ttp': 'ttp',
 'tulisan': 'tulis',
 'udh': 'udh',
 'ulang': 'ulang',
 'untuk': 'untuk',
 'update': 'update',
 'via': 'via',
 'wajib': 'wajib',
 'ya': 'ya',
 'yang': 'yang',
 'yg': 'yg'}

In [ ]:
df1_baru = df.copy()
df1_baru = df1_baru['d1(0)']
df1_baru = df1_baru.str.replace("_", " ")
df1_baru = df1_baru.str.strip()

df2_baru = df.copy()
df2_baru = df2_baru['d2(1)']
df2_baru = df2_baru.str.replace("_", " ")
df2_baru = df2_baru.str.strip()

In [ ]:
df1_baru

0     april pembayaran angka kenaikan berita menyeba...
1     performa aplikasi masi lambat padhal update me...
2     aplikasi tolong dibenerin eror mulu terdaftar ...
3     aplikasi gak bener daptar gak login tolong pen...
4     aplikasi perbaharui download ulang eror masuk ...
5     ok iuran dinaikan kelas melarat gini pemerinta...
6     berat hati kecewa kebijakan iuran bpjs lunasi ...
7     lancar aja dikit update buka cek premi ga load...
8     loginiuran kualitas nol perbaiki dongrakyat di...
9     program kesehatan nasional gundulmu merantau d...
10    daftar akun memasukkan email simpan email pesa...
11      update akses cacha nya muncul login trial error
12    download daftar online nomer antrian periksa s...
13    tolong bantu login masuk notif transaksi prose...
14    aplikasi terhenti pilih menu rubah data pesert...
Name: d1(0), dtype: object

In [ ]:
df2_baru

0     bawa surat rujukan specialis mata dilayani lay...
1               bagus bikin kesel diperbarui diperbarui
2                      membatu mengecek bayar perusahan
3     reset password mengenali email daftar status e...
4     aplikasi membantu kalah mendaftar puskesmasrum...
5     peningkatan signifikan lanjutkan info kamar ko...
6     bagusaplikasi membantu pemegang kartu bpjs kes...
7              aplikasinya membantu terima kasih mobile
8     keren riwayat pelayanan anak istri riwayat pel...
9        mohon dibantu aplikasi dibuka mohon maaf salah
10                            lumayan membantu aplikasi
11         keren seandainya menu pendaftaran calon bayi
12    ya kalo terdaftar gabisa masuk logo gabisa nom...
13    gimana sih merubah tanggal lahir peserta aplil...
14    bermanfaat sekalitolong jaga kualitas pelayana...
Name: d2(1), dtype: object

In [ ]:
count1 = 0
for i in range(len(df1_baru)):
    data1 = df1_baru[i].split()
    new_op1 = []
    # print(count, data)
    for j in range(len(data1)):
        new_op1.append(stem_collection[data1[j]])
    df1_baru[i] = " ".join(new_op1)
    count1 += 1

In [ ]:
count2 = 0
for i in range(len(df2_baru)):
    data2 = df2_baru[i].split()
    new_op2 = []
    # print(count, data)
    for j in range(len(data2)):
        new_op2.append(stem_collection[data2[j]])
    df2_baru[i] = " ".join(new_op2)
    count2 += 1

In [ ]:
dict_items = stem_collection.items()
sorted_stem = sorted(dict_items)

In [ ]:
for i in range(len(df1_baru)):
    if len(df1_baru[i]) < 1:
        df1_baru.drop([i], inplace=True)

In [ ]:
for i in range(len(df2_baru)):
    if len(df2_baru[i]) < 1:
        df2_baru.drop([i], inplace=True)

In [ ]:
df1_baru = df1_baru.reset_index()
df1_baru.drop(columns=["index"], inplace=True)
df1_baru

                                                d1(0)
0   april bayar angka naik berita sebar media baya...
1   performa aplikasi mas lambat padhal update but...
2   aplikasi tolong dibenerin eror mulu daftar log...
3   aplikasi gak bener daptar gak login tolong jel...
4   aplikasi baharu download ulang eror masuk tuli...
5   ok iur naik kelas melarat gin perintah benarbe...
6   berat hati kecewa bijak iur bpjs lunas jandes ...
7   lancar aja dikit update buka cek premi ga load...
8   loginiuran kualitas nol baik dongrakyat tekan ...
9   program sehat nasional gundul rantau pakai fas...
10  daftar akun masuk email simpan email pesan tra...
11    update akses cacha nya muncul login trial error
12  download daftar online nomer antri periksa solusi
13  tolong bantu login masuk notif transaksi prose...
14  aplikasi henti pilih menu rubah data serta men...

In [ ]:
df2_baru = df2_baru.reset_index()
df2_baru.drop(columns=["index"], inplace=True)
df2_baru

                                                d2(1)
0   bawa surat rujuk specialis mata layan layak pa...
1                         bagus bikin kesel baru baru
2                                batu ecek bayar usah
3   reset password nali email daftar status email ...
4   aplikasi bantu kalah daftar puskesmasrumah sak...
5         tingkat signifikan lanjut info kamar kosong
6   bagusaplikasi bantu pegang kartu bpjs kesehata...
7                  aplikasi bantu terima kasih mobile
8        keren riwayat layan anak istri riwayat layan
9          mohon bantu aplikasi buka mohon maaf salah
10                             lumayan bantu aplikasi
11                  keren anda menu daftar calon bayi
12  ya kalo daftar gabisa masuk logo gabisa nomer ...
13  gimana sih rubah tanggal lahir serta aplilasi ...
14  manfaat sekalitolong jaga kualitas layan rumah...

In [ ]:
dataclean = [df1_baru["d1(0)"], df2_baru["d2(1)"]]
header = ["d1(0)","d2(1)"]
dfclean = pd.concat(dataclean, axis = 1, keys=header)

In [ ]:
dfclean

                                                d1(0)                                              d2(1)
0   april bayar angka naik berita sebar media baya...  bawa surat rujuk specialis mata layan layak pa...
1   performa aplikasi mas lambat padhal update but...                        bagus bikin kesel baru baru
2   aplikasi tolong dibenerin eror mulu daftar log...                               batu ecek bayar usah
3   aplikasi gak bener daptar gak login tolong jel...  reset password nali email daftar status email ...
4   aplikasi baharu download ulang eror masuk tuli...  aplikasi bantu kalah daftar puskesmasrumah sak...
5   ok iur naik kelas melarat gin perintah benarbe...        tingkat signifikan lanjut info kamar kosong
6   berat hati kecewa bijak iur bpjs lunas jandes ...  bagusaplikasi bantu pegang kartu bpjs kesehata...
7   lancar aja dikit update buka cek premi ga load...                 aplikasi bantu terima kasih mobile
8   loginiuran kualitas nol baik dongrakyat tekan ...       keren riwayat layan anak istri riwayat layan
9   program sehat nasional gundul rantau pakai fas...         mohon bantu aplikasi buka mohon maaf salah
10  daftar akun masuk email simpan email pesan tra...                             lumayan bantu aplikasi
11    update akses cacha nya muncul login trial error                  keren anda menu daftar calon bayi
12  download daftar online nomer antri periksa solusi  ya kalo daftar gabisa masuk logo gabisa nomer ...
13  tolong bantu login masuk notif transaksi prose...  gimana sih rubah tanggal lahir serta aplilasi ...
14  aplikasi henti pilih menu rubah data serta men...  manfaat sekalitolong jaga kualitas layan rumah...

In [ ]:
df1_list = df1_baru.stack().tolist()
df1_list

['april bayar angka naik berita sebar media bayar bpjs tarif april fool pasti bpjs perintah',
 'performa aplikasi mas lambat padhal update butuh berulangulang login erro transaksi tolong baik akses jam pagi banget',
 'aplikasi tolong dibenerin eror mulu daftar login sandi salah daftar pdahal daftar nya mudah bikin ribet tolong baik biar mudah',
 'aplikasi gak bener daptar gak login tolong jelas nya',
 'aplikasi baharu download ulang eror masuk tulis nya transaksi proses silah coba baharu aplikasi masuk ya masuk protes keras aplikasi eror bintang saulasan lengkapaplikasi baharu download ulang eror masuk tulis nya transaksi proses silah coba baharu aplikasi masuk ya masuk protes keras aplikasi eror bintang kasih bintang nilai',
 'ok iur naik kelas melarat gin perintah benarbenar perah rakyat ini layan susah mudah layan sulit bayar iyuran mudah tarif bayar naik lagiulasan lengkapok iur naik kelas melarat gin perintah benarbenar perah rakyat ini layan susah mudah layan sulit bayar iyuran mudah tarif bayar naik lagiiiiiiii covid efek',
 'berat hati kecewa bijak iur bpjs lunas jandes via tokped masuk kaya saldo deposit app iur nya ngikut atur gak adil sih bayar lunasulasan lengkapdengan berat hati kecewa bijak iur bpjs lunas jandes via tokped masuk kaya saldo deposit app iur nya ngikut atur gak adil sih bayar lunas atur iur ya ngikut atur iur kaya gin ngrasa bohong',
 'lancar aja dikit update buka cek premi ga loading tolong kalo update aplikasi tingkat keluh ga respon kalo oke kasi bintang',
 'loginiuran kualitas nol baik dongrakyat tekan wajib bayar aja kadang sulit error lahujungnya blokir dipersulitmana pakai layan aja enak',
 'program sehat nasional gundul rantau pakai faskes kampung rantau indonesia henti setor kena sanksi ribet bener',
 'daftar akun masuk email simpan email pesan transaksi proses silah coba coba puluh kali',
 'update akses cacha nya muncul login trial error',
 'download daftar online nomer antri periksa solusi',
 'tolong bantu login masuk notif transaksi prosessilahkan coba ulang kali coba login',
 'aplikasi henti pilih menu rubah data serta menu kartumohon baik']

In [ ]:
term1 = []

for index,kalimat in enumerate(df1_list):
  for kata in kalimat.split():
    if kata not in term1 and len(kata)>1:
      term1.append(kata)

In [ ]:
term1.sort()
term1

['adil',
 'aja',
 'akses',
 'akun',
 'angka',
 'antri',
 'aplikasi',
 'app',
 'april',
 'atur',
 'baharu',
 'baik',
 'banget',
 'bantu',
 'bayar',
 'benarbenar',
 'bener',
 'berat',
 'berita',
 'berulangulang',
 'biar',
 'bijak',
 'bikin',
 'bintang',
 'blokir',
 'bohong',
 'bpjs',
 'buka',
 'butuh',
 'cacha',
 'cek',
 'coba',
 'covid',
 'daftar',
 'daptar',
 'data',
 'deposit',
 'dibenerin',
 'dikit',
 'dipersulitmana',
 'dongrakyat',
 'download',
 'efek',
 'email',
 'enak',
 'eror',
 'erro',
 'error',
 'faskes',
 'fool',
 'ga',
 'gak',
 'gin',
 'gundul',
 'hati',
 'henti',
 'indonesia',
 'ini',
 'iur',
 'iyuran',
 'jam',
 'jandes',
 'jelas',
 'kadang',
 'kali',
 'kalo',
 'kampung',
 'kartumohon',
 'kasi',
 'kasih',
 'kaya',
 'kecewa',
 'kelas',
 'keluh',
 'kena',
 'keras',
 'kualitas',
 'lagiiiiiiii',
 'lagiulasan',
 'lahujungnya',
 'lambat',
 'lancar',
 'layan',
 'lengkapaplikasi',
 'lengkapdengan',
 'lengkapok',
 'loading',
 'login',
 'loginiuran',
 'lunas',
 'lunasulasan',
 'mas',
 'masuk',
 'media',
 'melarat',
 'menu',
 'mudah',
 'mulu',
 'muncul',
 'naik',
 'nasional',
 'ngikut',
 'ngrasa',
 'nilai',
 'nol',
 'nomer',
 'notif',
 'nya',
 'ok',
 'oke',
 'online',
 'padhal',
 'pagi',
 'pakai',
 'pasti',
 'pdahal',
 'perah',
 'performa',
 'periksa',
 'perintah',
 'pesan',
 'pilih',
 'premi',
 'program',
 'proses',
 'prosessilahkan',
 'protes',
 'puluh',
 'rakyat',
 'rantau',
 'respon',
 'ribet',
 'rubah',
 'salah',
 'saldo',
 'sandi',
 'sanksi',
 'saulasan',
 'sebar',
 'sehat',
 'serta',
 'setor',
 'sih',
 'silah',
 'simpan',
 'solusi',
 'sulit',
 'susah',
 'tarif',
 'tekan',
 'tingkat',
 'tokped',
 'tolong',
 'transaksi',
 'trial',
 'tulis',
 'ulang',
 'update',
 'via',
 'wajib',
 'ya']

In [ ]:
df2_list = df2_baru.stack().tolist()
df2_list

['bawa surat rujuk specialis mata layan layak pasien',
 'bagus bikin kesel baru baru',
 'batu ecek bayar usah',
 'reset password nali email daftar status email daftar trus login',
 'aplikasi bantu kalah daftar puskesmasrumah sakit terdekatpraktis',
 'tingkat signifikan lanjut info kamar kosong',
 'bagusaplikasi bantu pegang kartu bpjs kesehatanfitur fiturnya familier masyarakat',
 'aplikasi bantu terima kasih mobile',
 'keren riwayat layan anak istri riwayat layan',
 'mohon bantu aplikasi buka mohon maaf salah',
 'lumayan bantu aplikasi',
 'keren anda menu daftar calon bayi',
 'ya kalo daftar gabisa masuk logo gabisa nomer bpjs paswordnya gabisa masukmohon bantu',
 'gimana sih rubah tanggal lahir serta aplilasi mohon cerah nya',
 'manfaat sekalitolong jaga kualitas layan rumah sakit kait']

In [ ]:
term2 = []

for index,kalimat in enumerate(df2_list):
  for kata in kalimat.split():
    if kata not in term2 and len(kata)>1:
      term2.append(kata)

In [ ]:
term2.sort()
term2

['anak',
 'anda',
 'aplikasi',
 'aplilasi',
 'bagus',
 'bagusaplikasi',
 'bantu',
 'baru',
 'batu',
 'bawa',
 'bayar',
 'bayi',
 'bikin',
 'bpjs',
 'buka',
 'calon',
 'cerah',
 'daftar',
 'ecek',
 'email',
 'familier',
 'fiturnya',
 'gabisa',
 'gimana',
 'info',
 'istri',
 'jaga',
 'kait',
 'kalah',
 'kalo',
 'kamar',
 'kartu',
 'kasih',
 'keren',
 'kesehatanfitur',
 'kesel',
 'kosong',
 'kualitas',
 'lahir',
 'lanjut',
 'layak',
 'layan',
 'login',
 'logo',
 'lumayan',
 'maaf',
 'manfaat',
 'masuk',
 'masukmohon',
 'masyarakat',
 'mata',
 'menu',
 'mobile',
 'mohon',
 'nali',
 'nomer',
 'nya',
 'pasien',
 'password',
 'paswordnya',
 'pegang',
 'puskesmasrumah',
 'reset',
 'riwayat',
 'rubah',
 'rujuk',
 'rumah',
 'sakit',
 'salah',
 'sekalitolong',
 'serta',
 'signifikan',
 'sih',
 'specialis',
 'status',
 'surat',
 'tanggal',
 'terdekatpraktis',
 'terima',
 'tingkat',
 'trus',
 'usah',
 'ya']

# **Term Weighting (Pembobotan Kata)**

In [ ]:
def hitung_kemunculan_kata(list_kata):
  jumlah_kata = {}
  for kata in list_kata:
    if kata not in jumlah_kata:
      jumlah_kata[kata] = 0
    jumlah_kata[kata] += 1

  return jumlah_kata

In [ ]:
#Dataframe Kelas 0

In [ ]:
rtf_r = pd.DataFrame({'Term':term1})

In [ ]:
for i, kalimat in enumerate(df1_list):
  freq_kata_1 = hitung_kemunculan_kata(kalimat.split())
  result1 = []
  for kata in term1:
    if kata in freq_kata_1: 
      result1.append(freq_kata_1[kata]) 
    else:
      result1.append(0)
  rtf_r['d'+str(i+1)+'(0)'] = result1

In [ ]:
rtf_r.set_index('Term', inplace = True)
rtf_r

        d1(0)  d2(0)  d3(0)  d4(0)  ...  d12(0)  d13(0)  d14(0)  d15(0)
Term                                ...
adil        0      0      0      0  ...       0       0       0       0
aja         0      0      0      0  ...       0       0       0       0
akses       0      1      0      0  ...       1       0       0       0
akun        0      0      0      0  ...       0       0       0       0
angka       1      0      0      0  ...       0       0       0       0
...       ...    ...    ...    ...  ...     ...     ...     ...     ...
ulang       0      0      0      0  ...       0       0       1       0
update      0      1      0      0  ...       1       0       0       0
via         0      0      0      0  ...       0       0       0       0
wajib       0      0      0      0  ...       0       0       0       0
ya          0      0      0      0  ...       0       0       0       0

[161 rows x 15 columns]

In [ ]:
#Dataframe Kelas 1

In [ ]:
rtf_r2 = pd.DataFrame({'Term':term2})

In [ ]:
for i, kalimat in enumerate(df2_list):
  freq_kata_2 = hitung_kemunculan_kata(kalimat.split())
  result2 = []
  for kata in term2:
    if kata in freq_kata_2: 
      result2.append(freq_kata_2[kata]) 
    else:
      result2.append(0)
  rtf_r2['d'+str(i+1)+'(1)'] = result2

In [ ]:
rtf_r2.set_index('Term', inplace = True)
rtf_r2

          d1(1)  d2(1)  d3(1)  d4(1)  ...  d12(1)  d13(1)  d14(1)  d15(1)
Term                                  ...
anak          0      0      0      0  ...       0       0       0       0
anda          0      0      0      0  ...       1       0       0       0
aplikasi      0      0      0      0  ...       0       0       0       0
aplilasi      0      0      0      0  ...       0       0       1       0
bagus         0      1      0      0  ...       0       0       0       0
...         ...    ...    ...    ...  ...     ...     ...     ...     ...
terima        0      0      0      0  ...       0       0       0       0
tingkat       0      0      0      0  ...       0       0       0       0
trus          0      0      0      1  ...       0       0       0       0
usah          0      0      1      0  ...       0       0       0       0
ya            0      0      0      0  ...       0       1       0       0

[83 rows x 15 columns]

In [ ]:
rtf_gabungan = pd.concat([rtf_r,rtf_r2], axis = 1)
rtf_gabungan.head(30)

               d1(0)  d2(0)  d3(0)  d4(0)  ...  d12(1)  d13(1)  d14(1)  d15(1)
adil             0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
aja              0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
akses            0.0    1.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
akun             0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
angka            1.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
antri            0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
aplikasi         0.0    1.0    1.0    1.0  ...     0.0     0.0     0.0     0.0
app              0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
april            2.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
atur             0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
baharu           0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
baik             0.0    1.0    1.0    0.0  ...     NaN     NaN     NaN     NaN
banget           0.0    1.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
bantu            0.0    0.0    0.0    0.0  ...     0.0     1.0     0.0     0.0
bayar            2.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
benarbenar       0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
bener            0.0    0.0    0.0    1.0  ...     NaN     NaN     NaN     NaN
berat            0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
berita           1.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
berulangulang    0.0    1.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
biar             0.0    0.0    1.0    0.0  ...     NaN     NaN     NaN     NaN
bijak            0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
bikin            0.0    0.0    1.0    0.0  ...     0.0     0.0     0.0     0.0
bintang          0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
blokir           0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
bohong           0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
bpjs             2.0    0.0    0.0    0.0  ...     0.0     1.0     0.0     0.0
buka             0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
butuh            0.0    1.0    0.0    0.0  ...     NaN     NaN     NaN     NaN
cacha            0.0    0.0    0.0    0.0  ...     NaN     NaN     NaN     NaN

[30 rows x 30 columns]

In [ ]:
rtf_complete = rtf_gabungan.fillna(0)
rtf_complete.head(30)

               d1(0)  d2(0)  d3(0)  d4(0)  ...  d12(1)  d13(1)  d14(1)  d15(1)
adil             0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
aja              0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
akses            0.0    1.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
akun             0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
angka            1.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
antri            0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
aplikasi         0.0    1.0    1.0    1.0  ...     0.0     0.0     0.0     0.0
app              0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
april            2.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
atur             0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
baharu           0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
baik             0.0    1.0    1.0    0.0  ...     0.0     0.0     0.0     0.0
banget           0.0    1.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
bantu            0.0    0.0    0.0    0.0  ...     0.0     1.0     0.0     0.0
bayar            2.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
benarbenar       0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
bener            0.0    0.0    0.0    1.0  ...     0.0     0.0     0.0     0.0
berat            0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
berita           1.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
berulangulang    0.0    1.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
biar             0.0    0.0    1.0    0.0  ...     0.0     0.0     0.0     0.0
bijak            0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
bikin            0.0    0.0    1.0    0.0  ...     0.0     0.0     0.0     0.0
bintang          0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
blokir           0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
bohong           0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
bpjs             2.0    0.0    0.0    0.0  ...     0.0     1.0     0.0     0.0
buka             0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
butuh            0.0    1.0    0.0    0.0  ...     0.0     0.0     0.0     0.0
cacha            0.0    0.0    0.0    0.0  ...     0.0     0.0     0.0     0.0

[30 rows x 30 columns]

# **Naive Bayes**

In [ ]:
n = len(rtf_complete.columns)
v = len(rtf_complete.index)

In [ ]:
print(n)
print(v)

30
221

In [ ]:
sumd10 = rtf_complete['d1(0)'].sum()
sumd20 = rtf_complete['d2(0)'].sum()
sumd30 = rtf_complete['d3(0)'].sum()
sumd40 = rtf_complete['d4(0)'].sum()
sumd50 = rtf_complete['d5(0)'].sum()
sumd60 = rtf_complete['d6(0)'].sum()
sumd70 = rtf_complete['d7(0)'].sum()
sumd80 = rtf_complete['d8(0)'].sum()
sumd90 = rtf_complete['d9(0)'].sum()
sumd100 = rtf_complete['d10(0)'].sum()
sumd110 = rtf_complete['d11(0)'].sum()
sumd120 = rtf_complete['d12(0)'].sum()
sumd130 = rtf_complete['d13(0)'].sum()
sumd140 = rtf_complete['d14(0)'].sum()
sumd150 = rtf_complete['d15(0)'].sum()


sumd11 = rtf_complete['d1(1)'].sum()
sumd21 = rtf_complete['d2(1)'].sum()
sumd31 = rtf_complete['d3(1)'].sum()
sumd41 = rtf_complete['d4(1)'].sum()
sumd51 = rtf_complete['d5(1)'].sum()
sumd61 = rtf_complete['d6(1)'].sum()
sumd71 = rtf_complete['d7(1)'].sum()
sumd81 = rtf_complete['d8(1)'].sum()
sumd91 = rtf_complete['d9(1)'].sum()
sumd101 = rtf_complete['d10(1)'].sum()
sumd111 = rtf_complete['d11(1)'].sum()
sumd121 = rtf_complete['d12(1)'].sum()
sumd131 = rtf_complete['d13(1)'].sum()
sumd141 = rtf_complete['d14(1)'].sum()
sumd151 = rtf_complete['d15(1)'].sum()

In [ ]:
total1 = np.sum([sumd10,sumd20,sumd30,sumd40,sumd50,sumd60,sumd70,sumd80,sumd90,sumd100,sumd110,sumd120,sumd130,sumd140,sumd150])
total1 = total1.item()
print(total1)
print(type(total1))


total2 = np.sum([sumd11,sumd21,sumd31,sumd41,sumd51,sumd61,sumd71,sumd81,sumd91,sumd101,sumd111,sumd121,sumd131,sumd141,sumd151])
total2 = total2.item()
print(total2)
print(type(total2))

323.0
<class 'float'>
108.0
<class 'float'>

In [ ]:
def pa(d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,total1,v):
  q = ((d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14+d15)+1)/((total1)+v)
  return q

def pb(d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,total2,v):
  q = ((d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12+d13+d14+d15)+1)/((total2)+v)
  return q

In [ ]:
rtf_complete['p(w|0)'] = pa(rtf_complete.loc[:,'d1(0)'],rtf_complete.loc[:,'d2(0)'],rtf_complete.loc[:,'d3(0)'],rtf_complete.loc[:,'d4(0)'],rtf_complete.loc[:,'d5(0)'],rtf_complete.loc[:,'d6(0)'],rtf_complete.loc[:,'d7(0)'],rtf_complete.loc[:,'d8(0)'],rtf_complete.loc[:,'d9(0)'],rtf_complete.loc[:,'d10(0)'],rtf_complete.loc[:,'d11(0)'],rtf_complete.loc[:,'d12(0)'],rtf_complete.loc[:,'d13(0)'],rtf_complete.loc[:,'d14(0)'],rtf_complete.loc[:,'d15(0)'],total1,v)

In [ ]:
rtf_complete['p(w|1)'] = pb(rtf_complete.loc[:,'d1(1)'],rtf_complete.loc[:,'d2(1)'],rtf_complete.loc[:,'d3(1)'],rtf_complete.loc[:,'d4(1)'],rtf_complete.loc[:,'d5(1)'],rtf_complete.loc[:,'d6(1)'],rtf_complete.loc[:,'d7(1)'],rtf_complete.loc[:,'d8(1)'],rtf_complete.loc[:,'d9(1)'],rtf_complete.loc[:,'d10(1)'],rtf_complete.loc[:,'d11(1)'],rtf_complete.loc[:,'d12(1)'],rtf_complete.loc[:,'d13(1)'],rtf_complete.loc[:,'d14(1)'],rtf_complete.loc[:,'d15(1)'],total2,v)

In [ ]:
rtf_complete

                 d1(0)  d2(0)  d3(0)  d4(0)  ...  d14(1)  d15(1)    p(w|0)    p(w|1)
adil               0.0    0.0    0.0    0.0  ...     0.0     0.0  0.005515  0.003040
aja                0.0    0.0    0.0    0.0  ...     0.0     0.0  0.007353  0.003040
akses              0.0    1.0    0.0    0.0  ...     0.0     0.0  0.005515  0.003040
akun               0.0    0.0    0.0    0.0  ...     0.0     0.0  0.003676  0.003040
angka              1.0    0.0    0.0    0.0  ...     0.0     0.0  0.003676  0.003040
...                ...    ...    ...    ...  ...     ...     ...       ...       ...
tanggal            0.0    0.0    0.0    0.0  ...     1.0     0.0  0.001838  0.006079
terdekatpraktis    0.0    0.0    0.0    0.0  ...     0.0     0.0  0.001838  0.006079
terima             0.0    0.0    0.0    0.0  ...     0.0     0.0  0.001838  0.006079
trus               0.0    0.0    0.0    0.0  ...     0.0     0.0  0.001838  0.006079
usah               0.0    0.0    0.0    0.0  ...     0.0     0.0  0.001838  0.006079

[221 rows x 32 columns]

In [ ]:
def p_a(nc,n):
  y = nc/n
  return y

In [ ]:
p__a = p_a(15,n)
p__b = p_a(15,n)

# **KFOLD**

In [ ]:
#data pisah per kelas 
kfd1 = rtf_complete[["d1(0)","d2(0)","d3(0)","d4(0)","d5(0)","d6(0)","d7(0)","d8(0)","d9(0)","d10(0)","d11(0)","d12(0)","d13(0)","d14(0)","d15(0)"]]
kfd2 = rtf_complete[["d1(1)","d2(1)","d3(1)","d4(1)","d5(1)","d6(1)","d7(1)","d8(1)","d9(1)","d10(1)","d11(1)","d12(1)","d13(1)","d14(1)","d15(1)"]]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#kfold1


train10,test10,train11,test11 = train_test_split(kfd1.transpose(),kfd2.transpose(), test_size=0.20)

train10 = train10.fillna(0)
test10  = test10.fillna(0)
train11 = train11.fillna(0)
test11  = test11.fillna(0)

kf10 = [train10,train11]
kftrain1 = pd.concat(kf10).transpose()

kf11 = [test10,test11]
kftest1 = pd.concat(kf11).transpose()

In [ ]:
#kfold2


train20x,test20,train21x,test21 = train_test_split(train10,train11, test_size=0.25)

frame20 = [train20x,test10]
train20 = pd.concat(frame20)

frame21 = [train21x,test11]
train21 = pd.concat(frame21)

train20 = train20.fillna(0)
test20  = test20.fillna(0)
train21 = train21.fillna(0)
test21  = test21.fillna(0)

kf20 = [train20,train21]
kftrain2 = pd.concat(kf20).transpose()

kf21 = [test20,test21]
kftest2 = pd.concat(kf21).transpose()

In [ ]:
#kfold3


train30x,test30,train31x,test31 = train_test_split(train20x,train21x, test_size=0.333)

frame30 = [train30x,test10,test20]
train30 = pd.concat(frame30)

frame31 = [train31x,test11,test21]
train31 = pd.concat(frame31)

train30 = train30.fillna(0)
test30  = test30.fillna(0)
train31 = train31.fillna(0)
test31  = test31.fillna(0)

kf30 = [train30,train31]
kftrain3 = pd.concat(kf30).transpose()

kf31 = [test30,test31]
kftest3 = pd.concat(kf31).transpose()

In [ ]:
#kfold4


train40x,test40,train41x,test41 = train_test_split(train30x,train31x, test_size=0.5)

frame40 = [train40x,test10,test20,test30]
train40 = pd.concat(frame40)

frame41 = [train41x,test11,test21,test31]
train41 = pd.concat(frame41)

train40 = train40.fillna(0)
test40  = test40.fillna(0)
train41 = train41.fillna(0)
test41  = test41.fillna(0)

kf40 = [train40,train41]
kftrain4 = pd.concat(kf40).transpose()

kf41 = [test40,test41]
kftest4 = pd.concat(kf41).transpose()

In [ ]:
#kfold5

test50 = train40x
frame50 = [test10,test20,test30,test40]
train50 = pd.concat(frame50)

test51 = train41x
frame51 = [test11,test21,test31,test41]
train51 = pd.concat(frame51)

train50 = train50.fillna(0)
test50  = test50.fillna(0)
train51 = train51.fillna(0)
test51  = test51.fillna(0)

kf50 = [train50,train51]
kftrain5 = pd.concat(kf50).transpose()

kf51 = [test50,test51]
kftest5 = pd.concat(kf51).transpose()

In [ ]:
print(kftrain1)
print(kftest1)

                 d10(0)  d6(0)  d9(0)  d15(0)  ...  d5(1)  d1(1)  d3(1)  d11(1)
adil                0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
aja                 0.0    0.0    2.0     0.0  ...    0.0    0.0    0.0     0.0
akses               0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
akun                0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
angka               0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
...                 ...    ...    ...     ...  ...    ...    ...    ...     ...
tanggal             0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
terdekatpraktis     0.0    0.0    0.0     0.0  ...    1.0    0.0    0.0     0.0
terima              0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
trus                0.0    0.0    0.0     0.0  ...    0.0    0.0    0.0     0.0
usah                0.0    0.0    0.0     0.0  ...    0.0    0.0    1.0     0.0

[221 rows x 24 columns]
                 d12(0)  d7(0)  d13(0)  d12(1)  d7(1)  d13(1)
adil                0.0    2.0     0.0     0.0    0.0     0.0
aja                 0.0    0.0     0.0     0.0    0.0     0.0
akses               1.0    0.0     0.0     0.0    0.0     0.0
akun                0.0    0.0     0.0     0.0    0.0     0.0
angka               0.0    0.0     0.0     0.0    0.0     0.0
...                 ...    ...     ...     ...    ...     ...
tanggal             0.0    0.0     0.0     0.0    0.0     0.0
terdekatpraktis     0.0    0.0     0.0     0.0    0.0     0.0
terima              0.0    0.0     0.0     0.0    0.0     0.0
trus                0.0    0.0     0.0     0.0    0.0     0.0
usah                0.0    0.0     0.0     0.0    0.0     0.0

[221 rows x 6 columns]

In [ ]:
print(kftrain2)
print(kftest2)

                 d1(0)  d3(0)  d2(0)  d10(0)  ...  d14(1)  d12(1)  d7(1)  d13(1)
adil               0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
aja                0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
akses              0.0    0.0    1.0     0.0  ...     0.0     0.0    0.0     0.0
akun               0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
angka              1.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
...                ...    ...    ...     ...  ...     ...     ...    ...     ...
tanggal            0.0    0.0    0.0     0.0  ...     1.0     0.0    0.0     0.0
terdekatpraktis    0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
terima             0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
trus               0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0
usah               0.0    0.0    0.0     0.0  ...     0.0     0.0    0.0     0.0

[221 rows x 24 columns]
                 d6(0)  d15(0)  d9(0)  d6(1)  d15(1)  d9(1)
adil               0.0     0.0    0.0    0.0     0.0    0.0
aja                0.0     0.0    2.0    0.0     0.0    0.0
akses              0.0     0.0    0.0    0.0     0.0    0.0
akun               0.0     0.0    0.0    0.0     0.0    0.0
angka              0.0     0.0    0.0    0.0     0.0    0.0
...                ...     ...    ...    ...     ...    ...
tanggal            0.0     0.0    0.0    0.0     0.0    0.0
terdekatpraktis    0.0     0.0    0.0    0.0     0.0    0.0
terima             0.0     0.0    0.0    0.0     0.0    0.0
trus               0.0     0.0    0.0    0.0     0.0    0.0
usah               0.0     0.0    0.0    0.0     0.0    0.0

[221 rows x 6 columns]

In [ ]:
print(kftrain3)
print(kftest3)

                 d5(0)  d14(0)  d2(0)  d3(0)  ...  d13(1)  d6(1)  d15(1)  d9(1)
adil               0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
aja                0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
akses              0.0     0.0    1.0    0.0  ...     0.0    0.0     0.0    0.0
akun               0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
angka              0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
...                ...     ...    ...    ...  ...     ...    ...     ...    ...
tanggal            0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
terdekatpraktis    0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
terima             0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
trus               0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0
usah               0.0     0.0    0.0    0.0  ...     0.0    0.0     0.0    0.0

[221 rows x 24 columns]
                 d11(0)  d4(0)  d8(0)  d11(1)  d4(1)  d8(1)
adil                0.0    0.0    0.0     0.0    0.0    0.0
aja                 0.0    0.0    1.0     0.0    0.0    0.0
akses               0.0    0.0    0.0     0.0    0.0    0.0
akun                1.0    0.0    0.0     0.0    0.0    0.0
angka               0.0    0.0    0.0     0.0    0.0    0.0
...                 ...    ...    ...     ...    ...    ...
tanggal             0.0    0.0    0.0     0.0    0.0    0.0
terdekatpraktis     0.0    0.0    0.0     0.0    0.0    0.0
terima              0.0    0.0    0.0     0.0    0.0    1.0
trus                0.0    0.0    0.0     0.0    1.0    0.0
usah                0.0    0.0    0.0     0.0    0.0    0.0

[221 rows x 6 columns]

In [ ]:
print(kftrain4)
print(kftest4)

                 d1(0)  d14(0)  d3(0)  d12(0)  ...  d9(1)  d11(1)  d4(1)  d8(1)
adil               0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0
aja                0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0
akses              0.0     0.0    0.0     1.0  ...    0.0     0.0    0.0    0.0
akun               0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0
angka              1.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0
...                ...     ...    ...     ...  ...    ...     ...    ...    ...
tanggal            0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0
terdekatpraktis    0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0
terima             0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    1.0
trus               0.0     0.0    0.0     0.0  ...    0.0     0.0    1.0    0.0
usah               0.0     0.0    0.0     0.0  ...    0.0     0.0    0.0    0.0

[221 rows x 24 columns]
                 d10(0)  d5(0)  d2(0)  d10(1)  d5(1)  d2(1)
adil                0.0    0.0    0.0     0.0    0.0    0.0
aja                 0.0    0.0    0.0     0.0    0.0    0.0
akses               0.0    0.0    1.0     0.0    0.0    0.0
akun                0.0    0.0    0.0     0.0    0.0    0.0
angka               0.0    0.0    0.0     0.0    0.0    0.0
...                 ...    ...    ...     ...    ...    ...
tanggal             0.0    0.0    0.0     0.0    0.0    0.0
terdekatpraktis     0.0    0.0    0.0     0.0    1.0    0.0
terima              0.0    0.0    0.0     0.0    0.0    0.0
trus                0.0    0.0    0.0     0.0    0.0    0.0
usah                0.0    0.0    0.0     0.0    0.0    0.0

[221 rows x 6 columns]

In [ ]:
print(kftrain5)
print(kftest5)

                 d12(0)  d7(0)  d13(0)  d6(0)  ...  d8(1)  d10(1)  d5(1)  d2(1)
adil                0.0    2.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
aja                 0.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
akses               1.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
akun                0.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
angka               0.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
...                 ...    ...     ...    ...  ...    ...     ...    ...    ...
tanggal             0.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
terdekatpraktis     0.0    0.0     0.0    0.0  ...    0.0     0.0    1.0    0.0
terima              0.0    0.0     0.0    0.0  ...    1.0     0.0    0.0    0.0
trus                0.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0
usah                0.0    0.0     0.0    0.0  ...    0.0     0.0    0.0    0.0

[221 rows x 24 columns]
                 d1(0)  d14(0)  d3(0)  d1(1)  d14(1)  d3(1)
adil               0.0     0.0    0.0    0.0     0.0    0.0
aja                0.0     0.0    0.0    0.0     0.0    0.0
akses              0.0     0.0    0.0    0.0     0.0    0.0
akun               0.0     0.0    0.0    0.0     0.0    0.0
angka              1.0     0.0    0.0    0.0     0.0    0.0
...                ...     ...    ...    ...     ...    ...
tanggal            0.0     0.0    0.0    0.0     1.0    0.0
terdekatpraktis    0.0     0.0    0.0    0.0     0.0    0.0
terima             0.0     0.0    0.0    0.0     0.0    0.0
trus               0.0     0.0    0.0    0.0     0.0    0.0
usah               0.0     0.0    0.0    0.0     0.0    1.0

[221 rows x 6 columns]

In [ ]:
def totalsum(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12):
  total1 = np.sum([s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12])
  return total1

In [ ]:
def pka(d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,total1,v):
  q = ((d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12)+1)/((total1)+v)
  return q

def pkb(d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,total2,v):
  q = ((d1+d2+d3+d4+d5+d6+d7+d8+d9+d10+d11+d12)+1)/((total2)+v)
  return q

In [ ]:
def pk_a(nc,n):
  y = nc/n
  return y

In [ ]:
def hasil_kfold(paq,pbq):
  if paq > pbq:
    print('TERMASUK LABEL 0           = ' ,paq)
    print('sedangkan nb Label 1 hanya = ' ,pbq)
    return 0
  
  elif paq < pbq:
    print('TERMASUK LABEL 1           = ' ,pbq)
    print('sedangkan nb Label 0 hanya = ' ,paq)
    return 1

In [ ]:
def akurasi (hasila,hasilb):
  akurasi_a = 0
  if hasila==hasilb:
    akurasi_a = 1
    return akurasi_a
  
  else:
    akurasi_a = 0
    return akurasi_a

In [ ]:
def hitung_akurasi(d1,d2,d3,d4,d5,d6):
  akurasifinal = (d1+d2+d3+d4+d5+d6)/6
  return akurasifinal

**TRAINING KFOLD1**

In [ ]:
#training kfold1
n1 = len(kftrain1.columns)
v1 = len(kftrain1.index)

s1kt1 = kftrain1.iloc[:,0].sum()
s1kt2 = kftrain1.iloc[:,1].sum()
s1kt3 = kftrain1.iloc[:,2].sum()
s1kt4 = kftrain1.iloc[:,3].sum()
s1kt5 = kftrain1.iloc[:,4].sum()
s1kt6 = kftrain1.iloc[:,5].sum()
s1kt7 = kftrain1.iloc[:,6].sum()
s1kt8 = kftrain1.iloc[:,7].sum()
s1kt9 = kftrain1.iloc[:,8].sum()
s1kt10 = kftrain1.iloc[:,9].sum()
s1kt11 = kftrain1.iloc[:,10].sum()
s1kt12 = kftrain1.iloc[:,11].sum()

totalsum1 = totalsum(s1kt1,s1kt2,s1kt3,s1kt4,s1kt5,s1kt6,s1kt7,s1kt8,s1kt9,s1kt10,s1kt11,s1kt12)

kftrain1['p(w|0)'] = pka(kftrain1.iloc[:,0],kftrain1.iloc[:,1],kftrain1.iloc[:,2],kftrain1.iloc[:,3],kftrain1.iloc[:,4],kftrain1.iloc[:,5],kftrain1.iloc[:,6],kftrain1.iloc[:,7],kftrain1.iloc[:,8],kftrain1.iloc[:,9],kftrain1.iloc[:,10],kftrain1.iloc[:,11],totalsum1,v1)

s1kt13 = kftrain1.iloc[:,12].sum()
s1kt14 = kftrain1.iloc[:,13].sum()
s1kt15 = kftrain1.iloc[:,14].sum()
s1kt16 = kftrain1.iloc[:,15].sum()
s1kt17 = kftrain1.iloc[:,16].sum()
s1kt18 = kftrain1.iloc[:,17].sum()
s1kt19 = kftrain1.iloc[:,18].sum()
s1kt20 = kftrain1.iloc[:,19].sum()
s1kt21 = kftrain1.iloc[:,20].sum()
s1kt22 = kftrain1.iloc[:,21].sum()
s1kt23 = kftrain1.iloc[:,22].sum()
s1kt24 = kftrain1.iloc[:,23].sum()

totalsum2 = totalsum(s1kt13,s1kt14,s1kt15,s1kt16,s1kt17,s1kt18,s1kt19,s1kt20,s1kt21,s1kt22,s1kt23,s1kt24)

kftrain1['p(w|1)'] = pkb(kftrain1.iloc[:,12],kftrain1.iloc[:,13],kftrain1.iloc[:,14],kftrain1.iloc[:,15],kftrain1.iloc[:,16],kftrain1.iloc[:,17],kftrain1.iloc[:,18],kftrain1.iloc[:,19],kftrain1.iloc[:,20],kftrain1.iloc[:,21],kftrain1.iloc[:,22],kftrain1.iloc[:,23],totalsum2,v1)


pa_1k0 = pk_a(12,n1)
pa_1k1 = pk_a(12,n1)

**TEST KFOLD1**

In [ ]:
#DataTEST1
T1rslt1k0 = kftrain1.loc[kftest1.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt1k1 = kftrain1.loc[kftest1.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt1k0 = pa_1k0*np.prod(T1rslt1k0)
T1hasil_rslt1k1 = pa_1k1*np.prod(T1rslt1k1)

print("data ",list(pd.DataFrame([kftest1.iloc[:,0]>0]).index))

print("HASIL DATA TEST1")
T1hasil_kfold1 = hasil_kfold(T1hasil_rslt1k0,T1hasil_rslt1k1)
print()

#DataAsli1
T1rslt_1df0 = rtf_complete.loc[kftest1.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt_1df1 = rtf_complete.loc[kftest1.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt_1df0 = p__a*np.prod(T1rslt_1df0)
T1hasil_rslt_1df1 = p__b*np.prod(T1rslt_1df1)

print("HASIL DATA ASLI1")
T1hasil_df1 = hasil_kfold(T1hasil_rslt_1df0,T1hasil_rslt_1df1)
print()

T1akurasi1 = akurasi(T1hasil_kfold1,T1hasil_df1)
print(T1akurasi1)
print()
print("##########################################################################")

##########################################################################

#DataTEST2
T2rslt1k0 = kftrain1.loc[kftest1.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt1k1 = kftrain1.loc[kftest1.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt1k0 = pa_1k0*np.prod(T2rslt1k0)
T2hasil_rslt1k1 = pa_1k1*np.prod(T2rslt1k1)

print("data ",list(pd.DataFrame([kftest1.iloc[:,1]>0]).index))

print("HASIL DATA TEST2")
T2hasil_kfold1 = hasil_kfold(T2hasil_rslt1k0,T2hasil_rslt1k1)
print()

#DataAsli2
T2rslt_1df0 = rtf_complete.loc[kftest1.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt_1df1 = rtf_complete.loc[kftest1.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt_1df0 = p__a*np.prod(T2rslt_1df0)
T2hasil_rslt_1df1 = p__b*np.prod(T2rslt_1df1)

print("HASIL DATA ASLI2")
T2hasil_df1 = hasil_kfold(T2hasil_rslt_1df0,T2hasil_rslt_1df1)
print()

T2akurasi1 = akurasi(T2hasil_kfold1,T2hasil_df1)
print(T2akurasi1)
print()
print("##########################################################################")

##########################################################################

#DataTEST3
T3rslt1k0 = kftrain1.loc[kftest1.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt1k1 = kftrain1.loc[kftest1.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt1k0 = pa_1k0*np.prod(T3rslt1k0)
T3hasil_rslt1k1 = pa_1k1*np.prod(T3rslt1k1)

print("data ",list(pd.DataFrame([kftest1.iloc[:,2]>0]).index))

print("HASIL DATA TEST3")
T3hasil_kfold1 = hasil_kfold(T3hasil_rslt1k0,T3hasil_rslt1k1)
print()

#DataAsli3
T3rslt_1df0 = rtf_complete.loc[kftest1.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt_1df1 = rtf_complete.loc[kftest1.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt_1df0 = p__a*np.prod(T3rslt_1df0)
T3hasil_rslt_1df1 = p__b*np.prod(T3rslt_1df1)

print("HASIL DATA ASLI3")
T3hasil_df1 = hasil_kfold(T3hasil_rslt_1df0,T3hasil_rslt_1df1)
print()

T3akurasi1 = akurasi(T3hasil_kfold1,T3hasil_df1)
print(T3akurasi1)
print()
print("##########################################################################")

##########################################################################

#DataTEST4
T4rslt1k0 = kftrain1.loc[kftest1.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt1k1 = kftrain1.loc[kftest1.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt1k0 = pa_1k0*np.prod(T4rslt1k0)
T4hasil_rslt1k1 = pa_1k1*np.prod(T4rslt1k1)

print("data ",list(pd.DataFrame([kftest1.iloc[:,3]>0]).index))

print("HASIL DATA TEST4")
T4hasil_kfold1 = hasil_kfold(T4hasil_rslt1k0,T4hasil_rslt1k1)
print()

#DataAsli4
T4rslt_1df0 = rtf_complete.loc[kftest1.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt_1df1 = rtf_complete.loc[kftest1.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt_1df0 = p__a*np.prod(T4rslt_1df0)
T4hasil_rslt_1df1 = p__b*np.prod(T4rslt_1df1)

print("HASIL DATA ASLI4")
T4hasil_df1 = hasil_kfold(T4hasil_rslt_1df0,T4hasil_rslt_1df1)
print()

T4akurasi1 = akurasi(T4hasil_kfold1,T4hasil_df1)
print(T4akurasi1)
print()
print("##########################################################################")

##########################################################################

#DataTEST5
T5rslt1k0 = kftrain1.loc[kftest1.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt1k1 = kftrain1.loc[kftest1.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt1k0 = pa_1k0*np.prod(T5rslt1k0)
T5hasil_rslt1k1 = pa_1k1*np.prod(T5rslt1k1)

print("data ",list(pd.DataFrame([kftest1.iloc[:,4]>0]).index))

print("HASIL DATA TEST5")
T5hasil_kfold1 = hasil_kfold(T5hasil_rslt1k0,T5hasil_rslt1k1)
print()

#DataAsli5
T5rslt_1df0 = rtf_complete.loc[kftest1.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt_1df1 = rtf_complete.loc[kftest1.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt_1df0 = p__a*np.prod(T5rslt_1df0)
T5hasil_rslt_1df1 = p__b*np.prod(T5rslt_1df1)

print("HASIL DATA ASLI5")
T5hasil_df1 = hasil_kfold(T5hasil_rslt_1df0,T5hasil_rslt_1df1)
print()

T5akurasi1 = akurasi(T5hasil_kfold1,T5hasil_df1)
print(T5akurasi1)
print()
print("##########################################################################")

##########################################################################

#DataTEST6
T6rslt1k0 = kftrain1.loc[kftest1.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt1k1 = kftrain1.loc[kftest1.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt1k0 = pa_1k0*np.prod(T6rslt1k0)
T6hasil_rslt1k1 = pa_1k1*np.prod(T6rslt1k1)

print("data ",list(pd.DataFrame([kftest1.iloc[:,5]>0]).index))

print("HASIL DATA TEST6")
T6hasil_kfold1 = hasil_kfold(T6hasil_rslt1k0,T6hasil_rslt1k1)
print()

#DataAsli6
T6rslt_1df0 = rtf_complete.loc[kftest1.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt_1df1 = rtf_complete.loc[kftest1.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt_1df0 = p__a*np.prod(T6rslt_1df0)
T6hasil_rslt_1df1 = p__b*np.prod(T6rslt_1df1)

print("HASIL DATA ASLI6")
T6hasil_df1 = hasil_kfold(T6hasil_rslt_1df0,T6hasil_rslt_1df1)
print()

T6akurasi1 = akurasi(T6hasil_kfold1,T6hasil_df1)
print(T6akurasi1)
print()
print("##########################################################################")

##########################################################################

hasilakurasikfold1 = hitung_akurasi(T1akurasi1,T2akurasi1,T3akurasi1,T4akurasi1,T5akurasi1,T6akurasi1)
print("akurasi KFOLD1",hasilakurasikfold1)

data  ['d12(0)']
HASIL DATA TEST1
TERMASUK LABEL 0           =  1.0079253734130234e-19
sedangkan nb Label 1 hanya =  2.9682332854931935e-20

HASIL DATA ASLI1
TERMASUK LABEL 0           =  1.314223820339271e-18
sedangkan nb Label 1 hanya =  1.457010937892773e-20

1

##########################################################################
data  ['d7(0)']
HASIL DATA TEST2
TERMASUK LABEL 1           =  1.5929352200806756e-69
sedangkan nb Label 0 hanya =  6.639551692990132e-71

HASIL DATA ASLI2
TERMASUK LABEL 0           =  1.0907142905815867e-61
sedangkan nb Label 1 hanya =  1.5840033464797782e-69

0

##########################################################################
data  ['d13(0)']
HASIL DATA TEST3
TERMASUK LABEL 1           =  8.934382189334512e-18
sedangkan nb Label 0 hanya =  1.480390392200378e-18

HASIL DATA ASLI3
TERMASUK LABEL 0           =  2.723572412436432e-17
sedangkan nb Label 1 hanya =  1.4380697957001667e-17

0

##########################################################################
data  ['d12(1)']
HASIL DATA TEST4
TERMASUK LABEL 1           =  5.378498077979377e-15
sedangkan nb Label 0 hanya =  6.957834843341777e-16

HASIL DATA ASLI4
TERMASUK LABEL 1           =  1.1354999106848514e-13
sedangkan nb Label 0 hanya =  3.472554825856451e-16

1

##########################################################################
data  ['d7(1)']
HASIL DATA TEST5
TERMASUK LABEL 1           =  1.2326550188925223e-22
sedangkan nb Label 0 hanya =  2.6806525888644243e-24

HASIL DATA ASLI5
TERMASUK LABEL 1           =  2.9760223412277916e-20
sedangkan nb Label 0 hanya =  1.1983395887488976e-24

1

##########################################################################
data  ['d13(1)']
HASIL DATA TEST6
TERMASUK LABEL 1           =  5.442125446264488e-27
sedangkan nb Label 0 hanya =  4.9147319985970654e-27

HASIL DATA ASLI6
TERMASUK LABEL 1           =  6.598658196937111e-24
sedangkan nb Label 0 hanya =  6.414123015037893e-27

1

##########################################################################
akurasi KFOLD1 0.6666666666666666

**TRAINING KFOLD2**

In [ ]:
#training kfold2
n2 = len(kftrain2.columns)
v2 = len(kftrain2.index)

s2kt1 = kftrain2.iloc[:,0].sum()
s2kt2 = kftrain2.iloc[:,1].sum()
s2kt3 = kftrain2.iloc[:,2].sum()
s2kt4 = kftrain2.iloc[:,3].sum()
s2kt5 = kftrain2.iloc[:,4].sum()
s2kt6 = kftrain2.iloc[:,5].sum()
s2kt7 = kftrain2.iloc[:,6].sum()
s2kt8 = kftrain2.iloc[:,7].sum()
s2kt9 = kftrain2.iloc[:,8].sum()
s2kt10 = kftrain2.iloc[:,9].sum()
s2kt11 = kftrain2.iloc[:,10].sum()
s2kt12 = kftrain2.iloc[:,11].sum()

total2sum1 = totalsum(s2kt1,s2kt2,s2kt3,s2kt4,s2kt5,s2kt6,s2kt7,s2kt8,s2kt9,s2kt10,s2kt11,s2kt12)

kftrain2['p(w|0)'] = pka(kftrain2.iloc[:,0],kftrain2.iloc[:,1],kftrain2.iloc[:,2],kftrain2.iloc[:,3],kftrain2.iloc[:,4],kftrain2.iloc[:,5],kftrain2.iloc[:,6],kftrain2.iloc[:,7],kftrain2.iloc[:,8],kftrain2.iloc[:,9],kftrain2.iloc[:,10],kftrain2.iloc[:,11],total2sum1,v2)

s2kt13 = kftrain2.iloc[:,12].sum()
s2kt14 = kftrain2.iloc[:,13].sum()
s2kt15 = kftrain2.iloc[:,14].sum()
s2kt16 = kftrain2.iloc[:,15].sum()
s2kt17 = kftrain2.iloc[:,16].sum()
s2kt18 = kftrain2.iloc[:,17].sum()
s2kt19 = kftrain2.iloc[:,18].sum()
s2kt20 = kftrain2.iloc[:,19].sum()
s2kt21 = kftrain2.iloc[:,20].sum()
s2kt22 = kftrain2.iloc[:,21].sum()
s2kt23 = kftrain2.iloc[:,22].sum()
s2kt24 = kftrain2.iloc[:,23].sum()

total2sum2 = totalsum(s2kt13,s2kt14,s2kt15,s2kt16,s2kt17,s2kt18,s2kt19,s2kt20,s2kt21,s2kt22,s2kt23,s2kt24)

kftrain2['p(w|1)'] = pkb(kftrain2.iloc[:,12],kftrain2.iloc[:,13],kftrain2.iloc[:,14],kftrain2.iloc[:,15],kftrain2.iloc[:,16],kftrain2.iloc[:,17],kftrain2.iloc[:,18],kftrain2.iloc[:,19],kftrain2.iloc[:,20],kftrain2.iloc[:,21],kftrain2.iloc[:,22],kftrain2.iloc[:,23],total2sum2,v2)


pa_2k0 = pk_a(12,n2)
pa_2k1 = pk_a(12,n2)

**TEST KFOLD2**

In [ ]:
#DataTEST1
T1rslt2k0 = kftrain2.loc[kftest2.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt2k1 = kftrain2.loc[kftest2.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt2k0 = pa_2k0*np.prod(T1rslt2k0)
T1hasil_rslt2k1 = pa_2k1*np.prod(T1rslt2k1)

print("data ",list(pd.DataFrame([kftest2.iloc[:,0]>0]).index))

print("HASIL DATA TEST1")
T1hasil_k2fold1 = hasil_kfold(T1hasil_rslt2k0,T1hasil_rslt2k1)
print()

#DataAsli1
T1rslt_2df0 = rtf_complete.loc[kftest2.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt_2df1 = rtf_complete.loc[kftest2.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt_2df0 = p__a*np.prod(T1rslt_2df0)
T1hasil_rslt_2df1 = p__b*np.prod(T1rslt_2df1)

print("HASIL DATA ASLI1")
T1hasil_2df1 = hasil_kfold(T1hasil_rslt_2df0,T1hasil_rslt_2df1)
print()

T1akurasi21 = akurasi(T1hasil_k2fold1,T1hasil_2df1)
print(T1akurasi21)
print()
print("##########################################################################")

##########################################################################

#DataTEST2
T2rslt2k0 = kftrain2.loc[kftest2.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt2k1 = kftrain2.loc[kftest2.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt2k0 = pa_2k0*np.prod(T2rslt2k0)
T2hasil_rslt2k1 = pa_2k1*np.prod(T2rslt2k1)

print("data ",list(pd.DataFrame([kftest2.iloc[:,1]>0]).index))

print("HASIL DATA TEST2")
T2hasil_k2fold1 = hasil_kfold(T2hasil_rslt2k0,T2hasil_rslt2k1)
print()

#DataAsli2
T2rslt_2df0 = rtf_complete.loc[kftest2.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt_2df1 = rtf_complete.loc[kftest2.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt_2df0 = p__a*np.prod(T2rslt_2df0)
T2hasil_rslt_2df1 = p__b*np.prod(T2rslt_2df1)

print("HASIL DATA ASLI2")
T2hasil_2df1 = hasil_kfold(T2hasil_rslt_2df0,T2hasil_rslt_2df1)
print()

T2akurasi21 = akurasi(T2hasil_k2fold1,T2hasil_2df1)
print(T2akurasi21)
print()
print("##########################################################################")

##########################################################################

#DataTEST3
T3rslt2k0 = kftrain2.loc[kftest2.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt2k1 = kftrain2.loc[kftest2.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt2k0 = pa_2k0*np.prod(T3rslt2k0)
T3hasil_rslt2k1 = pa_2k1*np.prod(T3rslt2k1)

print("data ",list(pd.DataFrame([kftest2.iloc[:,2]>0]).index))

print("HASIL DATA TEST3")
T3hasil_k2fold1 = hasil_kfold(T3hasil_rslt2k0,T3hasil_rslt2k1)
print()

#DataAsli3
T3rslt_2df0 = rtf_complete.loc[kftest2.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt_2df1 = rtf_complete.loc[kftest2.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt_2df0 = p__a*np.prod(T3rslt_2df0)
T3hasil_rslt_2df1 = p__b*np.prod(T3rslt_2df1)

print("HASIL DATA ASLI3")
T3hasil_2df1 = hasil_kfold(T3hasil_rslt_2df0,T3hasil_rslt_2df1)
print()

T3akurasi21 = akurasi(T3hasil_k2fold1,T3hasil_2df1)
print(T3akurasi21)
print()
print("##########################################################################")

##########################################################################

#DataTEST4
T4rslt2k0 = kftrain2.loc[kftest2.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt2k1 = kftrain2.loc[kftest2.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt2k0 = pa_2k0*np.prod(T4rslt2k0)
T4hasil_rslt2k1 = pa_2k1*np.prod(T4rslt2k1)

print("data ",list(pd.DataFrame([kftest2.iloc[:,3]>0]).index))

print("HASIL DATA TEST4")
T4hasil_k2fold1 = hasil_kfold(T4hasil_rslt2k0,T4hasil_rslt2k1)
print()

#DataAsli4
T4rslt_2df0 = rtf_complete.loc[kftest2.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt_2df1 = rtf_complete.loc[kftest2.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt_2df0 = p__a*np.prod(T4rslt_2df0)
T4hasil_rslt_2df1 = p__b*np.prod(T4rslt_2df1)

print("HASIL DATA ASLI4")
T4hasil_2df1 = hasil_kfold(T4hasil_rslt_2df0,T4hasil_rslt_2df1)
print()

T4akurasi21 = akurasi(T4hasil_k2fold1,T4hasil_2df1)
print(T4akurasi21)
print()
print("##########################################################################")

##########################################################################

#DataTEST5
T5rslt2k0 = kftrain2.loc[kftest2.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt2k1 = kftrain2.loc[kftest2.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt2k0 = pa_2k0*np.prod(T5rslt2k0)
T5hasil_rslt2k1 = pa_2k1*np.prod(T5rslt2k1)

print("data ",list(pd.DataFrame([kftest2.iloc[:,4]>0]).index))

print("HASIL DATA TEST5")
T5hasil_k2fold1 = hasil_kfold(T5hasil_rslt2k0,T5hasil_rslt2k1)
print()

#DataAsli5
T5rslt_2df0 = rtf_complete.loc[kftest2.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt_2df1 = rtf_complete.loc[kftest2.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt_2df0 = p__a*np.prod(T4rslt_2df0)
T5hasil_rslt_2df1 = p__b*np.prod(T4rslt_2df1)

print("HASIL DATA ASLI5")
T5hasil_2df1 = hasil_kfold(T5hasil_rslt_2df0,T5hasil_rslt_2df1)
print()

T5akurasi21 = akurasi(T5hasil_k2fold1,T5hasil_2df1)
print(T5akurasi21)
print()
print("##########################################################################")

##########################################################################

#DataTEST6
T6rslt2k0 = kftrain2.loc[kftest2.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt2k1 = kftrain2.loc[kftest2.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt2k0 = pa_2k0*np.prod(T6rslt2k0)
T6hasil_rslt2k1 = pa_2k1*np.prod(T6rslt2k1)

print("data ",list(pd.DataFrame([kftest2.iloc[:,5]>0]).index))

print("HASIL DATA TEST6")
T6hasil_k2fold1 = hasil_kfold(T6hasil_rslt2k0,T6hasil_rslt2k1)
print()

#DataAsli6
T6rslt_2df0 = rtf_complete.loc[kftest2.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt_2df1 = rtf_complete.loc[kftest2.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt_2df0 = p__a*np.prod(T6rslt_2df0)
T6hasil_rslt_2df1 = p__b*np.prod(T6rslt_2df1)

print("HASIL DATA ASLI6")
T6hasil_2df1 = hasil_kfold(T6hasil_rslt_2df0,T6hasil_rslt_2df1)
print()

T6akurasi21 = akurasi(T6hasil_k2fold1,T6hasil_2df1)
print(T6akurasi21)
print()
print("##########################################################################")

##########################################################################

hasilakurasikfold2 = hitung_akurasi(T1akurasi21,T2akurasi21,T3akurasi21,T4akurasi21,T5akurasi21,T6akurasi21)
print("akurasi KFOLD2",hasilakurasikfold2)

data  ['d6(0)']
HASIL DATA TEST1
TERMASUK LABEL 1           =  1.159747689987457e-57
sedangkan nb Label 0 hanya =  3.3883716003330525e-59

HASIL DATA ASLI1
TERMASUK LABEL 0           =  1.4696987965293036e-51
sedangkan nb Label 1 hanya =  6.360105965689686e-58

0

##########################################################################
data  ['d15(0)']
HASIL DATA TEST2
TERMASUK LABEL 1           =  8.018138379370121e-22
sedangkan nb Label 0 hanya =  2.8396795221863336e-23

HASIL DATA ASLI2
TERMASUK LABEL 0           =  1.898169908578254e-21
sedangkan nb Label 1 hanya =  4.428604674446119e-22

0

##########################################################################
data  ['d9(0)']
HASIL DATA TEST3
TERMASUK LABEL 1           =  3.2145271535364046e-45
sedangkan nb Label 0 hanya =  5.375853192482936e-47

HASIL DATA ASLI3
TERMASUK LABEL 0           =  2.5409932354517524e-42
sedangkan nb Label 1 hanya =  4.9031348406315034e-45

0

##########################################################################
data  ['d6(1)']
HASIL DATA TEST4
TERMASUK LABEL 1           =  5.856871629998365e-16
sedangkan nb Label 0 hanya =  9.640481301189415e-17

HASIL DATA ASLI4
TERMASUK LABEL 1           =  2.5233331348552262e-14
sedangkan nb Label 0 hanya =  3.858394250951612e-17

1

##########################################################################
data  ['d15(1)']
HASIL DATA TEST5
TERMASUK LABEL 1           =  2.4695866208459967e-20
sedangkan nb Label 0 hanya =  2.2102172281016963e-22

HASIL DATA ASLI5
TERMASUK LABEL 1           =  2.5233331348552262e-14
sedangkan nb Label 0 hanya =  3.858394250951612e-17

1

##########################################################################
data  ['d9(1)']
HASIL DATA TEST6
TERMASUK LABEL 1           =  7.215665848157986e-13
sedangkan nb Label 0 hanya =  2.2510523838277283e-14

HASIL DATA ASLI6
TERMASUK LABEL 1           =  2.3348716913457264e-11
sedangkan nb Label 0 hanya =  6.296899417553031e-14

1

##########################################################################
akurasi KFOLD2 0.5

**TRAINING KFOLD3**

In [ ]:
#training kfold3
n3 = len(kftrain3.columns)
v3 = len(kftrain3.index)

s3kt1 = kftrain3.iloc[:,0].sum()
s3kt2 = kftrain3.iloc[:,1].sum()
s3kt3 = kftrain3.iloc[:,2].sum()
s3kt4 = kftrain3.iloc[:,3].sum()
s3kt5 = kftrain3.iloc[:,4].sum()
s3kt6 = kftrain3.iloc[:,5].sum()
s3kt7 = kftrain3.iloc[:,6].sum()
s3kt8 = kftrain3.iloc[:,7].sum()
s3kt9 = kftrain3.iloc[:,8].sum()
s3kt10 = kftrain3.iloc[:,9].sum()
s3kt11 = kftrain3.iloc[:,10].sum()
s3kt12 = kftrain3.iloc[:,11].sum()

total3sum1 = totalsum(s3kt1,s3kt2,s3kt3,s3kt4,s3kt5,s3kt6,s3kt7,s3kt8,s3kt9,s3kt10,s3kt11,s3kt12)

kftrain3['p(w|0)'] = pka(kftrain3.iloc[:,0],kftrain3.iloc[:,1],kftrain3.iloc[:,2],kftrain3.iloc[:,3],kftrain3.iloc[:,4],kftrain3.iloc[:,5],kftrain3.iloc[:,6],kftrain3.iloc[:,7],kftrain3.iloc[:,8],kftrain3.iloc[:,9],kftrain3.iloc[:,10],kftrain3.iloc[:,11],total3sum1,v3)

s3kt13 = kftrain3.iloc[:,12].sum()
s3kt14 = kftrain3.iloc[:,13].sum()
s3kt15 = kftrain3.iloc[:,14].sum()
s3kt16 = kftrain3.iloc[:,15].sum()
s3kt17 = kftrain3.iloc[:,16].sum()
s3kt18 = kftrain3.iloc[:,17].sum()
s3kt19 = kftrain3.iloc[:,18].sum()
s3kt20 = kftrain3.iloc[:,19].sum()
s3kt21 = kftrain3.iloc[:,20].sum()
s3kt22 = kftrain3.iloc[:,21].sum()
s3kt23 = kftrain3.iloc[:,22].sum()
s3kt24 = kftrain3.iloc[:,23].sum()

total3sum2 = totalsum(s3kt13,s3kt14,s3kt15,s3kt16,s3kt17,s3kt18,s3kt19,s3kt20,s3kt21,s3kt22,s3kt23,s3kt24)

kftrain3['p(w|1)'] = pkb(kftrain3.iloc[:,12],kftrain3.iloc[:,13],kftrain3.iloc[:,14],kftrain3.iloc[:,15],kftrain3.iloc[:,16],kftrain3.iloc[:,17],kftrain3.iloc[:,18],kftrain3.iloc[:,19],kftrain3.iloc[:,20],kftrain3.iloc[:,21],kftrain3.iloc[:,22],kftrain3.iloc[:,23],total3sum2,v3)


pa_3k0 = pk_a(12,n3)
pa_3k1 = pk_a(12,n3)

**TEST KFOLD3**

In [ ]:
#DataTEST1
T1rslt3k0 = kftrain3.loc[kftest3.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt3k1 = kftrain3.loc[kftest3.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt3k0 = pa_3k0*np.prod(T1rslt3k0)
T1hasil_rslt3k1 = pa_3k1*np.prod(T1rslt3k1)

print("data ",list(pd.DataFrame([kftest3.iloc[:,0]>0]).index))

print("HASIL DATA TEST1")
T1hasil_k3fold1 = hasil_kfold(T1hasil_rslt3k0,T1hasil_rslt3k1)
print()

#DataAsli1
T1rslt_3df0 = rtf_complete.loc[kftest3.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt_3df1 = rtf_complete.loc[kftest3.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt_3df0 = p__a*np.prod(T1rslt_3df0)
T1hasil_rslt_3df1 = p__b*np.prod(T1rslt_3df1)

print("HASIL DATA ASLI1")
T1hasil_3df1 = hasil_kfold(T1hasil_rslt_3df0,T1hasil_rslt_3df1)
print()

T1akurasi31 = akurasi(T1hasil_k3fold1,T1hasil_3df1)
print(T1akurasi31)
print()
print("##########################################################################")

##########################################################################

#DataTEST2
T2rslt3k0 = kftrain3.loc[kftest3.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt3k1 = kftrain3.loc[kftest3.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt3k0 = pa_3k0*np.prod(T2rslt3k0)
T2hasil_rslt3k1 = pa_3k1*np.prod(T2rslt3k1)

print("data ",list(pd.DataFrame([kftest3.iloc[:,1]>0]).index))

print("HASIL DATA TEST2")
T2hasil_k3fold1 = hasil_kfold(T2hasil_rslt3k0,T2hasil_rslt3k1)
print()

#DataAsli2
T2rslt_3df0 = rtf_complete.loc[kftest3.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt_3df1 = rtf_complete.loc[kftest3.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt_3df0 = p__a*np.prod(T2rslt_3df0)
T2hasil_rslt_3df1 = p__b*np.prod(T2rslt_3df1)

print("HASIL DATA ASLI2")
T2hasil_3df1 = hasil_kfold(T2hasil_rslt_3df0,T2hasil_rslt_3df1)
print()

T2akurasi31 = akurasi(T2hasil_k3fold1,T2hasil_3df1)
print(T2akurasi31)
print()
print("##########################################################################")

##########################################################################

#DataTEST3
T3rslt3k0 = kftrain3.loc[kftest3.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt3k1 = kftrain3.loc[kftest3.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt3k0 = pa_3k0*np.prod(T3rslt3k0)
T3hasil_rslt3k1 = pa_3k1*np.prod(T3rslt3k1)

print("data ",list(pd.DataFrame([kftest3.iloc[:,2]>0]).index))

print("HASIL DATA TEST3")
T3hasil_k3fold1 = hasil_kfold(T3hasil_rslt3k0,T3hasil_rslt3k1)
print()

#DataAsli3
T3rslt_3df0 = rtf_complete.loc[kftest3.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt_3df1 = rtf_complete.loc[kftest3.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt_3df0 = p__a*np.prod(T3rslt_3df0)
T3hasil_rslt_3df1 = p__b*np.prod(T3rslt_3df1)

print("HASIL DATA ASLI3")
T3hasil_3df1 = hasil_kfold(T3hasil_rslt_3df0,T3hasil_rslt_3df1)
print()

T3akurasi31 = akurasi(T3hasil_k3fold1,T3hasil_3df1)
print(T3akurasi31)
print()
print("##########################################################################")

##########################################################################

#DataTEST4
T4rslt3k0 = kftrain3.loc[kftest3.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt3k1 = kftrain3.loc[kftest3.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt3k0 = pa_3k0*np.prod(T4rslt3k0)
T4hasil_rslt3k1 = pa_3k1*np.prod(T4rslt3k1)

print("data ",list(pd.DataFrame([kftest3.iloc[:,3]>0]).index))

print("HASIL DATA TEST4")
T4hasil_k3fold1 = hasil_kfold(T4hasil_rslt3k0,T4hasil_rslt3k1)
print()

#DataAsli4
T4rslt_3df0 = rtf_complete.loc[kftest3.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt_3df1 = rtf_complete.loc[kftest3.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt_3df0 = p__a*np.prod(T4rslt_3df0)
T4hasil_rslt_3df1 = p__b*np.prod(T4rslt_3df1)

print("HASIL DATA ASLI4")
T4hasil_3df1 = hasil_kfold(T4hasil_rslt_3df0,T4hasil_rslt_3df1)
print()

T4akurasi31 = akurasi(T4hasil_k3fold1,T4hasil_3df1)
print(T4akurasi31)
print()
print("##########################################################################")

##########################################################################

#DataTEST5
T5rslt3k0 = kftrain3.loc[kftest3.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt3k1 = kftrain3.loc[kftest3.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt3k0 = pa_3k0*np.prod(T5rslt3k0)
T5hasil_rslt3k1 = pa_3k1*np.prod(T5rslt3k1)

print("data ",list(pd.DataFrame([kftest3.iloc[:,4]>0]).index))

print("HASIL DATA TEST5")
T5hasil_k3fold1 = hasil_kfold(T5hasil_rslt3k0,T5hasil_rslt3k1)
print()

#DataAsli5
T5rslt_3df0 = rtf_complete.loc[kftest3.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt_3df1 = rtf_complete.loc[kftest3.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt_3df0 = p__a*np.prod(T5rslt_3df0)
T5hasil_rslt_3df1 = p__b*np.prod(T5rslt_3df1)

print("HASIL DATA ASLI5")
T5hasil_3df1 = hasil_kfold(T5hasil_rslt_3df0,T5hasil_rslt_3df1)
print()

T5akurasi31 = akurasi(T5hasil_k3fold1,T5hasil_3df1)
print(T5akurasi31)
print()
print("##########################################################################")

##########################################################################

#DataTEST6
T6rslt3k0 = kftrain3.loc[kftest3.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt3k1 = kftrain3.loc[kftest3.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt3k0 = pa_3k0*np.prod(T6rslt3k0)
T6hasil_rslt3k1 = pa_3k1*np.prod(T6rslt3k1)

print("data ",list(pd.DataFrame([kftest3.iloc[:,5]>0]).index))

print("HASIL DATA TEST6")
T6hasil_k3fold1 = hasil_kfold(T6hasil_rslt3k0,T6hasil_rslt3k1)
print()

#DataAsli6
T6rslt_3df0 = rtf_complete.loc[kftest3.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt_3df1 = rtf_complete.loc[kftest3.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt_3df0 = p__a*np.prod(T6rslt_3df0)
T6hasil_rslt_3df1 = p__b*np.prod(T6rslt_3df1)

print("HASIL DATA ASLI6")
T6hasil_3df1 = hasil_kfold(T6hasil_rslt_3df0,T6hasil_rslt_3df1)
print()

T6akurasi31 = akurasi(T6hasil_k3fold1,T6hasil_3df1)
print(T6akurasi31)
print()
print("##########################################################################")

##########################################################################





hasilakurasikfold3 = hitung_akurasi(T1akurasi31,T2akurasi31,T3akurasi31,T4akurasi31,T5akurasi31,T6akurasi31)
print("akurasi KFOLD3",hasilakurasikfold3)

data  ['d11(0)']
HASIL DATA TEST1
TERMASUK LABEL 0           =  4.608000000000002e-29
sedangkan nb Label 1 hanya =  4.8857959255935795e-30

HASIL DATA ASLI1
TERMASUK LABEL 0           =  4.753997058204557e-27
sedangkan nb Label 1 hanya =  1.119236152053217e-29

1

##########################################################################
data  ['d4(0)']
HASIL DATA TEST2
TERMASUK LABEL 0           =  1.4515200000000004e-18
sedangkan nb Label 1 hanya =  3.427978919166146e-20

HASIL DATA ASLI2
TERMASUK LABEL 0           =  1.6865872361020647e-17
sedangkan nb Label 1 hanya =  7.285054689463866e-20

1

##########################################################################
data  ['d8(0)']
HASIL DATA TEST3
TERMASUK LABEL 1           =  1.6199225222026926e-44
sedangkan nb Label 0 hanya =  2.1233664e-46

HASIL DATA ASLI3
TERMASUK LABEL 0           =  4.076176648537186e-42
sedangkan nb Label 1 hanya =  9.806269681263007e-45

0

##########################################################################
data  ['d11(1)']
HASIL DATA TEST4
TERMASUK LABEL 1           =  2.493331916234287e-07
sedangkan nb Label 0 hanya =  7.200000000000001e-08

HASIL DATA ASLI4
TERMASUK LABEL 1           =  9.828344040003719e-07
sedangkan nb Label 0 hanya =  6.832757162120903e-08

1

##########################################################################
data  ['d4(1)']
HASIL DATA TEST5
TERMASUK LABEL 1           =  2.2853192794440976e-20
sedangkan nb Label 0 hanya =  3.8400000000000015e-21

HASIL DATA ASLI5
TERMASUK LABEL 1           =  4.196191501131185e-18
sedangkan nb Label 0 hanya =  8.213898877120443e-21

1

##########################################################################
data  ['d8(1)']
HASIL DATA TEST6
TERMASUK LABEL 1           =  2.5778599437912e-12
sedangkan nb Label 0 hanya =  5.760000000000001e-13

HASIL DATA ASLI6
TERMASUK LABEL 1           =  3.632022630982241e-11
sedangkan nb Label 0 hanya =  4.617726239538889e-13

1

##########################################################################
akurasi KFOLD3 0.8333333333333334

**TRAINING KFOLD4**

In [ ]:
#training kfold4
n4 = len(kftrain4.columns)
v4 = len(kftrain4.index)

s4kt1 = kftrain4.iloc[:,0].sum()
s4kt2 = kftrain4.iloc[:,1].sum()
s4kt3 = kftrain4.iloc[:,2].sum()
s4kt4 = kftrain4.iloc[:,3].sum()
s4kt5 = kftrain4.iloc[:,4].sum()
s4kt6 = kftrain4.iloc[:,5].sum()
s4kt7 = kftrain4.iloc[:,6].sum()
s4kt8 = kftrain4.iloc[:,7].sum()
s4kt9 = kftrain4.iloc[:,8].sum()
s4kt10 = kftrain4.iloc[:,9].sum()
s4kt11 = kftrain4.iloc[:,10].sum()
s4kt12 = kftrain4.iloc[:,11].sum()

total4sum1 = totalsum(s4kt1,s4kt2,s4kt3,s4kt4,s4kt5,s4kt6,s4kt7,s4kt8,s4kt9,s4kt10,s4kt11,s4kt12)

kftrain4['p(w|0)'] = pka(kftrain4.iloc[:,0],kftrain4.iloc[:,1],kftrain4.iloc[:,2],kftrain4.iloc[:,3],kftrain4.iloc[:,4],kftrain4.iloc[:,5],kftrain4.iloc[:,6],kftrain4.iloc[:,7],kftrain4.iloc[:,8],kftrain4.iloc[:,9],kftrain4.iloc[:,10],kftrain4.iloc[:,11],total4sum1,v4)

s4kt13 = kftrain4.iloc[:,12].sum()
s4kt14 = kftrain4.iloc[:,13].sum()
s4kt15 = kftrain4.iloc[:,14].sum()
s4kt16 = kftrain4.iloc[:,15].sum()
s4kt17 = kftrain4.iloc[:,16].sum()
s4kt18 = kftrain4.iloc[:,17].sum()
s4kt19 = kftrain4.iloc[:,18].sum()
s4kt20 = kftrain4.iloc[:,19].sum()
s4kt21 = kftrain4.iloc[:,20].sum()
s4kt22 = kftrain4.iloc[:,21].sum()
s4kt23 = kftrain4.iloc[:,22].sum()
s4kt24 = kftrain4.iloc[:,23].sum()

total4sum2 = totalsum(s4kt13,s4kt14,s4kt15,s4kt16,s4kt17,s4kt18,s4kt19,s4kt20,s4kt21,s4kt22,s4kt23,s4kt24)

kftrain4['p(w|1)'] = pkb(kftrain4.iloc[:,12],kftrain4.iloc[:,13],kftrain4.iloc[:,14],kftrain4.iloc[:,15],kftrain4.iloc[:,16],kftrain4.iloc[:,17],kftrain4.iloc[:,18],kftrain4.iloc[:,19],kftrain4.iloc[:,20],kftrain4.iloc[:,21],kftrain4.iloc[:,22],kftrain4.iloc[:,23],total4sum2,v4)


pa_4k0 = pk_a(12,n3)
pa_4k1 = pk_a(12,n3)

**TEST KFOLD4**

In [ ]:
#DataTEST1
T1rslt4k0 = kftrain4.loc[kftest4.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt4k1 = kftrain4.loc[kftest4.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt4k0 = pa_4k0*np.prod(T1rslt4k0)
T1hasil_rslt4k1 = pa_4k1*np.prod(T1rslt4k1)

print("data ",list(pd.DataFrame([kftest4.iloc[:,0]>0]).index))

print("HASIL DATA TEST1")
T1hasil_k4fold1 = hasil_kfold(T1hasil_rslt4k0,T1hasil_rslt4k1)
print()

#DataAsli1
T1rslt_4df0 = rtf_complete.loc[kftest4.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt_4df1 = rtf_complete.loc[kftest4.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt_4df0 = p__a*np.prod(T1rslt_4df0)
T1hasil_rslt_4df1 = p__b*np.prod(T1rslt_4df1)

print("HASIL DATA ASLI1")
T1hasil_4df1 = hasil_kfold(T1hasil_rslt_4df0,T1hasil_rslt_4df1)
print()

T1akurasi41 = akurasi(T1hasil_k4fold1,T1hasil_4df1)
print(T1akurasi41)
print()
print("##########################################################################")

##########################################################################

#DataTEST2
T2rslt4k0 = kftrain4.loc[kftest4.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt4k1 = kftrain4.loc[kftest4.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt4k0 = pa_4k0*np.prod(T2rslt4k0)
T2hasil_rslt4k1 = pa_4k1*np.prod(T2rslt4k1)

print("data ",list(pd.DataFrame([kftest4.iloc[:,1]>0]).index))

print("HASIL DATA TEST2")
T2hasil_k4fold1 = hasil_kfold(T2hasil_rslt4k0,T2hasil_rslt4k1)
print()

#DataAsli2
T2rslt_4df0 = rtf_complete.loc[kftest4.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt_4df1 = rtf_complete.loc[kftest4.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt_4df0 = p__a*np.prod(T2rslt_4df0)
T2hasil_rslt_4df1 = p__b*np.prod(T2rslt_4df1)

print("HASIL DATA ASLI2")
T2hasil_4df1 = hasil_kfold(T2hasil_rslt_4df0,T2hasil_rslt_4df1)
print()

T2akurasi41 = akurasi(T2hasil_k4fold1,T2hasil_4df1)
print(T2akurasi41)
print()
print("##########################################################################")

##########################################################################

#DataTEST3
T3rslt4k0 = kftrain4.loc[kftest4.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt4k1 = kftrain4.loc[kftest4.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt4k0 = pa_4k0*np.prod(T3rslt4k0)
T3hasil_rslt4k1 = pa_4k1*np.prod(T3rslt4k1)

print("data ",list(pd.DataFrame([kftest4.iloc[:,2]>0]).index))

print("HASIL DATA TEST3")
T3hasil_k4fold1 = hasil_kfold(T3hasil_rslt4k0,T3hasil_rslt4k1)
print()

#DataAsli3
T3rslt_4df0 = rtf_complete.loc[kftest4.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt_4df1 = rtf_complete.loc[kftest4.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt_4df0 = p__a*np.prod(T3rslt_4df0)
T3hasil_rslt_4df1 = p__b*np.prod(T3rslt_4df1)

print("HASIL DATA ASLI3")
T3hasil_4df1 = hasil_kfold(T3hasil_rslt_4df0,T3hasil_rslt_4df1)
print()

T3akurasi41 = akurasi(T3hasil_k4fold1,T3hasil_4df1)
print(T3akurasi41)
print()
print("##########################################################################")

##########################################################################

#DataTEST4
T4rslt4k0 = kftrain4.loc[kftest4.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt4k1 = kftrain4.loc[kftest4.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt4k0 = pa_4k0*np.prod(T4rslt4k0)
T4hasil_rslt4k1 = pa_4k1*np.prod(T4rslt4k1)

print("data ",list(pd.DataFrame([kftest4.iloc[:,3]>0]).index))

print("HASIL DATA TEST4")
T4hasil_k4fold1 = hasil_kfold(T4hasil_rslt4k0,T4hasil_rslt4k1)
print()

#DataAsli4
T4rslt_4df0 = rtf_complete.loc[kftest4.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt_4df1 = rtf_complete.loc[kftest4.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt_4df0 = p__a*np.prod(T4rslt_4df0)
T4hasil_rslt_4df1 = p__b*np.prod(T4rslt_4df1)

print("HASIL DATA ASLI4")
T4hasil_4df1 = hasil_kfold(T4hasil_rslt_4df0,T4hasil_rslt_4df1)
print()

T4akurasi41 = akurasi(T4hasil_k4fold1,T4hasil_4df1)
print(T4akurasi41)
print()
print("##########################################################################")

##########################################################################

#DataTEST5
T5rslt4k0 = kftrain4.loc[kftest4.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt4k1 = kftrain4.loc[kftest4.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt4k0 = pa_4k0*np.prod(T5rslt4k0)
T5hasil_rslt4k1 = pa_4k1*np.prod(T5rslt4k1)

print("data ",list(pd.DataFrame([kftest4.iloc[:,4]>0]).index))

print("HASIL DATA TEST5")
T5hasil_k4fold1 = hasil_kfold(T5hasil_rslt4k0,T5hasil_rslt4k1)
print()

#DataAsli5
T5rslt_4df0 = rtf_complete.loc[kftest4.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt_4df1 = rtf_complete.loc[kftest4.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt_4df0 = p__a*np.prod(T5rslt_4df0)
T5hasil_rslt_4df1 = p__b*np.prod(T5rslt_4df1)

print("HASIL DATA ASLI5")
T5hasil_4df1 = hasil_kfold(T5hasil_rslt_4df0,T5hasil_rslt_4df1)
print()

T5akurasi41 = akurasi(T5hasil_k4fold1,T5hasil_4df1)
print(T5akurasi41)
print()
print("##########################################################################")

##########################################################################

#DataTEST6
T6rslt4k0 = kftrain4.loc[kftest4.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt4k1 = kftrain4.loc[kftest4.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt4k0 = pa_4k0*np.prod(T6rslt4k0)
T6hasil_rslt4k1 = pa_4k1*np.prod(T6rslt4k1)

print("data ",list(pd.DataFrame([kftest4.iloc[:,5]>0]).index))

print("HASIL DATA TEST6")
T6hasil_k4fold1 = hasil_kfold(T6hasil_rslt4k0,T6hasil_rslt4k1)
print()

#DataAsli6
T6rslt_4df0 = rtf_complete.loc[kftest4.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt_4df1 = rtf_complete.loc[kftest4.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt_4df0 = p__a*np.prod(T6rslt_4df0)
T6hasil_rslt_4df1 = p__b*np.prod(T6rslt_4df1)

print("HASIL DATA ASLI6")
T6hasil_4df1 = hasil_kfold(T6hasil_rslt_4df0,T6hasil_rslt_4df1)
print()

T6akurasi41 = akurasi(T6hasil_k4fold1,T6hasil_4df1)
print(T6akurasi41)
print()
print("##########################################################################")

##########################################################################





hasilakurasikfold4 = hitung_akurasi(T1akurasi41,T2akurasi41,T3akurasi41,T4akurasi41,T5akurasi41,T6akurasi41)
print("akurasi KFOLD4",hasilakurasikfold4)

data  ['d10(0)']
HASIL DATA TEST1
TERMASUK LABEL 1           =  2.130809364812437e-38
sedangkan nb Label 0 hanya =  8.305678605046485e-40

HASIL DATA ASLI1
TERMASUK LABEL 0           =  1.1505162024137744e-36
sedangkan nb Label 1 hanya =  8.730347590784869e-39

0

##########################################################################
data  ['d5(0)']
HASIL DATA TEST2
TERMASUK LABEL 0           =  7.026558587082029e-49
sedangkan nb Label 1 hanya =  3.572542179507769e-49

HASIL DATA ASLI2
TERMASUK LABEL 0           =  2.618132492680676e-43
sedangkan nb Label 1 hanya =  1.811932572918396e-49

1

##########################################################################
data  ['d2(0)']
HASIL DATA TEST3
TERMASUK LABEL 0           =  4.1844356662811314e-42
sedangkan nb Label 1 hanya =  1.3303700508714493e-42

HASIL DATA ASLI3
TERMASUK LABEL 0           =  3.8805201694074e-39
sedangkan nb Label 1 hanya =  8.065656812838823e-43

1

##########################################################################
data  ['d10(1)']
HASIL DATA TEST4
TERMASUK LABEL 1           =  1.690133835061806e-14
sedangkan nb Label 0 hanya =  2.030224430719239e-15

HASIL DATA ASLI4
TERMASUK LABEL 1           =  4.4158329859966457e-13
sedangkan nb Label 0 hanya =  1.6976934704187092e-15

1

##########################################################################
data  ['d5(1)']
HASIL DATA TEST5
TERMASUK LABEL 1           =  2.726022314615817e-16
sedangkan nb Label 0 hanya =  6.5774009634532595e-18

HASIL DATA ASLI5
TERMASUK LABEL 1           =  6.039893141940701e-15
sedangkan nb Label 0 hanya =  4.6811400838751175e-18

1

##########################################################################
data  ['d2(1)']
HASIL DATA TEST6
TERMASUK LABEL 1           =  5.414062051647986e-11
sedangkan nb Label 0 hanya =  2.176085904944263e-11

HASIL DATA ASLI6
TERMASUK LABEL 1           =  1.0242303819369918e-09
sedangkan nb Label 0 hanya =  1.1418377610496163e-11

1

##########################################################################
akurasi KFOLD4 0.8333333333333334

**TRAINING KFOLD5**

In [ ]:
#training kfold5
n5 = len(kftrain5.columns)
v5 = len(kftrain5.index)

s5kt1 = kftrain5.iloc[:,0].sum()
s5kt2 = kftrain5.iloc[:,1].sum()
s5kt3 = kftrain5.iloc[:,2].sum()
s5kt4 = kftrain5.iloc[:,3].sum()
s5kt5 = kftrain5.iloc[:,4].sum()
s5kt6 = kftrain5.iloc[:,5].sum()
s5kt7 = kftrain5.iloc[:,6].sum()
s5kt8 = kftrain5.iloc[:,7].sum()
s5kt9 = kftrain5.iloc[:,8].sum()
s5kt10 = kftrain5.iloc[:,9].sum()
s5kt11 = kftrain5.iloc[:,10].sum()
s5kt12 = kftrain5.iloc[:,11].sum()

total5sum1 = totalsum(s5kt1,s5kt2,s5kt3,s5kt4,s5kt5,s5kt6,s5kt7,s5kt8,s5kt9,s5kt10,s5kt11,s5kt12)

kftrain5['p(w|0)'] = pka(kftrain5.iloc[:,0],kftrain5.iloc[:,1],kftrain5.iloc[:,2],kftrain5.iloc[:,3],kftrain5.iloc[:,4],kftrain5.iloc[:,5],kftrain5.iloc[:,6],kftrain5.iloc[:,7],kftrain5.iloc[:,8],kftrain5.iloc[:,9],kftrain5.iloc[:,10],kftrain5.iloc[:,11],total5sum1,v5)

s5kt13 = kftrain5.iloc[:,12].sum()
s5kt14 = kftrain5.iloc[:,13].sum()
s5kt15 = kftrain5.iloc[:,14].sum()
s5kt16 = kftrain5.iloc[:,15].sum()
s5kt17 = kftrain5.iloc[:,16].sum()
s5kt18 = kftrain5.iloc[:,17].sum()
s5kt19 = kftrain5.iloc[:,18].sum()
s5kt20 = kftrain5.iloc[:,19].sum()
s5kt21 = kftrain5.iloc[:,20].sum()
s5kt22 = kftrain5.iloc[:,21].sum()
s5kt23 = kftrain5.iloc[:,22].sum()
s5kt24 = kftrain5.iloc[:,23].sum()

total5sum2 = totalsum(s5kt13,s5kt14,s5kt15,s5kt16,s5kt17,s5kt18,s5kt19,s5kt20,s5kt21,s5kt22,s5kt23,s5kt24)

kftrain5['p(w|1)'] = pkb(kftrain5.iloc[:,12],kftrain5.iloc[:,13],kftrain5.iloc[:,14],kftrain5.iloc[:,15],kftrain5.iloc[:,16],kftrain5.iloc[:,17],kftrain5.iloc[:,18],kftrain5.iloc[:,19],kftrain5.iloc[:,20],kftrain5.iloc[:,21],kftrain5.iloc[:,22],kftrain5.iloc[:,23],total5sum2,v5)


pa_5k0 = pk_a(12,n5)
pa_5k1 = pk_a(12,n5)

**TEST KFOLD5**

In [ ]:
#DataTEST1
T1rslt5k0 = kftrain5.loc[kftest5.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt5k1 = kftrain5.loc[kftest5.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt5k0 = pa_5k0*np.prod(T1rslt5k0)
T1hasil_rslt5k1 = pa_5k1*np.prod(T1rslt5k1)

print("data ",list(pd.DataFrame([kftest5.iloc[:,0]>0]).index))

print("HASIL DATA TEST1")
T1hasil_k5fold1 = hasil_kfold(T1hasil_rslt5k0,T1hasil_rslt5k1)
print()

#DataAsli1
T1rslt_5df0 = rtf_complete.loc[kftest5.iloc[:,0]>0]["p(w|0)"].to_numpy()
T1rslt_5df1 = rtf_complete.loc[kftest5.iloc[:,0]>0]["p(w|1)"].to_numpy()

T1hasil_rslt_5df0 = p__a*np.prod(T1rslt_5df0)
T1hasil_rslt_5df1 = p__b*np.prod(T1rslt_5df1)

print("HASIL DATA ASLI1")
T1hasil_5df1 = hasil_kfold(T1hasil_rslt_5df0,T1hasil_rslt_5df1)
print()

T1akurasi51 = akurasi(T1hasil_k5fold1,T1hasil_5df1)
print(T1akurasi51)
print()
print("##########################################################################")

##########################################################################

#DataTEST2
T2rslt5k0 = kftrain5.loc[kftest5.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt5k1 = kftrain5.loc[kftest5.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt5k0 = pa_5k0*np.prod(T2rslt5k0)
T2hasil_rslt5k1 = pa_5k1*np.prod(T2rslt5k1)

print("data ",list(pd.DataFrame([kftest5.iloc[:,1]>0]).index))

print("HASIL DATA TEST2")
T2hasil_k5fold1 = hasil_kfold(T2hasil_rslt5k0,T2hasil_rslt5k1)
print()

#DataAsli2
T2rslt_5df0 = rtf_complete.loc[kftest5.iloc[:,1]>0]["p(w|0)"].to_numpy()
T2rslt_5df1 = rtf_complete.loc[kftest5.iloc[:,1]>0]["p(w|1)"].to_numpy()

T2hasil_rslt_5df0 = p__a*np.prod(T2rslt_5df0)
T2hasil_rslt_5df1 = p__b*np.prod(T2rslt_5df1)

print("HASIL DATA ASLI2")
T2hasil_5df1 = hasil_kfold(T2hasil_rslt_5df0,T2hasil_rslt_5df1)
print()

T2akurasi51 = akurasi(T2hasil_k5fold1,T2hasil_5df1)
print(T2akurasi51)
print()
print("##########################################################################")

##########################################################################

#DataTEST3
T3rslt5k0 = kftrain5.loc[kftest5.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt5k1 = kftrain5.loc[kftest5.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt5k0 = pa_5k0*np.prod(T3rslt5k0)
T3hasil_rslt5k1 = pa_5k1*np.prod(T3rslt5k1)

print("data ",list(pd.DataFrame([kftest5.iloc[:,2]>0]).index))

print("HASIL DATA TEST3")
T3hasil_k5fold1 = hasil_kfold(T3hasil_rslt5k0,T3hasil_rslt5k1)
print()

#DataAsli3
T3rslt_5df0 = rtf_complete.loc[kftest5.iloc[:,2]>0]["p(w|0)"].to_numpy()
T3rslt_5df1 = rtf_complete.loc[kftest5.iloc[:,2]>0]["p(w|1)"].to_numpy()

T3hasil_rslt_5df0 = p__a*np.prod(T3rslt_5df0)
T3hasil_rslt_5df1 = p__b*np.prod(T3rslt_5df1)

print("HASIL DATA ASLI3")
T3hasil_5df1 = hasil_kfold(T3hasil_rslt_5df0,T3hasil_rslt_5df1)
print()

T3akurasi51 = akurasi(T3hasil_k5fold1,T3hasil_5df1)
print(T3akurasi51)
print()
print("##########################################################################")

##########################################################################

#Datatest4
T4rslt5k0 = kftrain5.loc[kftest5.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt5k1 = kftrain5.loc[kftest5.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt5k0 = pa_5k0*np.prod(T4rslt5k0)
T4hasil_rslt5k1 = pa_5k1*np.prod(T4rslt5k1)

print("data ",list(pd.DataFrame([kftest5.iloc[:,0]>3]).index))

print("HASIL DATA test5")
T4hasil_k5fold1 = hasil_kfold(T4hasil_rslt5k0,T4hasil_rslt5k1)
print()

#DataAsli4
T4rslt_5df0 = rtf_complete.loc[kftest5.iloc[:,3]>0]["p(w|0)"].to_numpy()
T4rslt_5df1 = rtf_complete.loc[kftest5.iloc[:,3]>0]["p(w|1)"].to_numpy()

T4hasil_rslt_5df0 = p__a*np.prod(T4rslt_5df0)
T4hasil_rslt_5df1 = p__b*np.prod(T4rslt_5df1)

print("HASIL DATA ASLI4")
T4hasil_5df1 = hasil_kfold(T4hasil_rslt_5df0,T4hasil_rslt_5df1)
print()

T4akurasi51 = akurasi(T4hasil_k5fold1,T4hasil_5df1)
print(T4akurasi51)
print()
print("##########################################################################")

##########################################################################

#DataTEST5
T5rslt5k0 = kftrain5.loc[kftest5.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt5k1 = kftrain5.loc[kftest5.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt5k0 = pa_5k0*np.prod(T5rslt5k0)
T5hasil_rslt5k1 = pa_5k1*np.prod(T5rslt5k1)

print("data ",list(pd.DataFrame([kftest5.iloc[:,4]>0]).index))

print("HASIL DATA TEST5")
T5hasil_k5fold1 = hasil_kfold(T5hasil_rslt5k0,T5hasil_rslt5k1)
print()

#DataAsli5
T5rslt_5df0 = rtf_complete.loc[kftest5.iloc[:,4]>0]["p(w|0)"].to_numpy()
T5rslt_5df1 = rtf_complete.loc[kftest5.iloc[:,4]>0]["p(w|1)"].to_numpy()

T5hasil_rslt_5df0 = p__a*np.prod(T5rslt_5df0)
T5hasil_rslt_5df1 = p__b*np.prod(T5rslt_5df1)

print("HASIL DATA ASLI5")
T5hasil_5df1 = hasil_kfold(T5hasil_rslt_5df0,T5hasil_rslt_5df1)
print()

T5akurasi51 = akurasi(T5hasil_k5fold1,T5hasil_5df1)
print(T5akurasi51)
print()
print("##########################################################################")

##########################################################################

#DataTEST6
T6rslt5k0 = kftrain5.loc[kftest5.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt5k1 = kftrain5.loc[kftest5.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt5k0 = pa_5k0*np.prod(T6rslt5k0)
T6hasil_rslt5k1 = pa_5k1*np.prod(T6rslt5k1)

print("data ",list(pd.DataFrame([kftest5.iloc[:,5]>0]).index))

print("HASIL DATA TEST6")
T6hasil_k5fold1 = hasil_kfold(T6hasil_rslt5k0,T6hasil_rslt5k1)
print()

#DataAsli6
T6rslt_5df0 = rtf_complete.loc[kftest5.iloc[:,5]>0]["p(w|0)"].to_numpy()
T6rslt_5df1 = rtf_complete.loc[kftest5.iloc[:,5]>0]["p(w|1)"].to_numpy()

T6hasil_rslt_5df0 = p__a*np.prod(T6rslt_5df0)
T6hasil_rslt_5df1 = p__b*np.prod(T6rslt_5df1)

print("HASIL DATA ASLI6")
T6hasil_5df1 = hasil_kfold(T6hasil_rslt_5df0,T6hasil_rslt_5df1)
print()

T6akurasi51 = akurasi(T6hasil_k5fold1,T6hasil_5df1)
print(T6akurasi51)
print()
print("##########################################################################")

##########################################################################





hasilakurasikfold5 = hitung_akurasi(T1akurasi51,T2akurasi51,T3akurasi51,T4akurasi51,T5akurasi51,T6akurasi51)
print("akurasi KFOLD5",hasilakurasikfold5)

data  ['d1(0)']
HASIL DATA TEST1
TERMASUK LABEL 0           =  2.3774812196851348e-30
sedangkan nb Label 1 hanya =  2.140083671033404e-30

HASIL DATA ASLI1
TERMASUK LABEL 0           =  6.860024615013791e-28
sedangkan nb Label 1 hanya =  1.865393586755362e-30

1

##########################################################################
data  ['d14(0)']
HASIL DATA TEST2
TERMASUK LABEL 0           =  1.3050205746515675e-23
sedangkan nb Label 1 hanya =  1.882540295171455e-24

HASIL DATA ASLI2
TERMASUK LABEL 0           =  4.787296166487801e-22
sedangkan nb Label 1 hanya =  9.422563137119398e-25

1

##########################################################################
data  ['d3(0)']
HASIL DATA TEST3
TERMASUK LABEL 0           =  2.4245830105058685e-38
sedangkan nb Label 1 hanya =  1.927379513245359e-38

HASIL DATA ASLI3
TERMASUK LABEL 0           =  1.7732424966124055e-35
sedangkan nb Label 1 hanya =  1.2737285238835067e-38

0

##########################################################################
data  ['d1(0)']
HASIL DATA test5
TERMASUK LABEL 1           =  2.5346791468516347e-20
sedangkan nb Label 0 hanya =  8.058795678102727e-22

HASIL DATA ASLI4
TERMASUK LABEL 1           =  2.331217500628437e-18
sedangkan nb Label 0 hanya =  3.9113804176764017e-22

1

##########################################################################
data  ['d14(1)']
HASIL DATA TEST5
TERMASUK LABEL 1           =  2.0170074591122728e-25
sedangkan nb Label 0 hanya =  4.567572011280487e-26

HASIL DATA ASLI5
TERMASUK LABEL 1           =  6.891931894578762e-23
sedangkan nb Label 0 hanya =  2.114716921321584e-26

1

##########################################################################
data  ['d3(1)']
HASIL DATA TEST6
TERMASUK LABEL 0           =  6.555931941116219e-11
sedangkan nb Label 1 hanya =  5.628808873611311e-11

HASIL DATA ASLI6
TERMASUK LABEL 1           =  6.828202546246613e-10
sedangkan nb Label 0 hanya =  5.709188805248082e-11

0

##########################################################################
akurasi KFOLD5 0.8333333333333334

In [ ]:
print("=====================================")
print(T1akurasi1,T2akurasi1,T3akurasi1,T4akurasi1,T5akurasi1,T6akurasi1)
print("akurasi KFOLD1",hasilakurasikfold1)
print("=====================================")
print(T1akurasi21,T2akurasi21,T3akurasi21,T4akurasi21,T5akurasi21,T6akurasi21)
print("akurasi KFOLD2",hasilakurasikfold2)
print("=====================================")
print(T1akurasi31,T2akurasi31,T3akurasi31,T4akurasi31,T5akurasi31,T6akurasi31)
print("akurasi KFOLD3",hasilakurasikfold3)
print("=====================================")
print(T1akurasi41,T2akurasi41,T3akurasi41,T4akurasi41,T5akurasi41,T6akurasi41)
print("akurasi KFOLD4",hasilakurasikfold4)
print("=====================================")
print(T1akurasi51,T2akurasi51,T3akurasi51,T4akurasi51,T5akurasi51,T6akurasi51)
print("akurasi KFOLD5",hasilakurasikfold5)

=====================================
1 0 0 1 1 1
akurasi KFOLD1 0.6666666666666666
=====================================
0 0 0 1 1 1
akurasi KFOLD2 0.5
=====================================
1 1 0 1 1 1
akurasi KFOLD3 0.8333333333333334
=====================================
0 1 1 1 1 1
akurasi KFOLD4 0.8333333333333334
=====================================
1 1 1 1 1 0
akurasi KFOLD5 0.8333333333333334

In [ ]:
qqq =(hasilakurasikfold1+hasilakurasikfold2+hasilakurasikfold3+hasilakurasikfold4+hasilakurasikfold5)/5

In [ ]:
print("rata-rata akurasi",qqq)

rata-rata akurasi 0.7333333333333334